INSERT INTO `pottery_baskets` (`periods`) VALUES
('MB/Rom(1), Pers(4), EB(5)'),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
('Byz (2), F (Unk)'),
('Mix ()'),
('Wadi Raba (F), EB (F)'),
('EB (All)'),
('EB (M), Byz  (S)'),
('EB (M)'),
('EB (All)'),
('EB (All)'),
('Wadi Raba (Main), EB (Main)'),
('EB1B (F), R/Byz (F)'),
('EB (F), R/Byz (F), ??? (F)'),
(''),
('EB  (F), KhK (F), WR (F)'),
('Chal  (F), Arab 1 (1), EB (F)'),
('EB (F), mod (F), N/K (F)'),
('EB  (F), R/Byz (F), N/K (F)'),
(''),
('EB (2), R/Byz (1), N/K (F)'),
('LB (F), EB (F), WR (1)'),
('WR (1), EB (2)'),
('WR (S), Pers (S), LB (S)'),
('EB (M), Chal (S), Byz (S)'),
('Hel bowl? (S), MB/LB (S), R/Byz (S)'),
('EB (M), IB  (S), R/Byz (S)'),
('Arab (M), Wadi Raba (F), EB (S)'),
('R/Byz (F), Gaza ware (F), S (F)'),
('EB  (M), Rom (F)'),
('Byz (F), Pers/Hellen (S)'),
('Pers ()'),
('Wadi Raba ( ), Chalco ( ), EB ()'),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
('Rom (1), EB (F), KK (F)'),
('KK (F), Byz (F), Pers ()'),
('Rom (), EB (), Iron ()'),
('KK (), EB (), R/Byz ()'),
(''),
('KK  (), WR (), EB ()'),
('No information; may go w/ R locus 309 ()'),
(''),
(''),
(''),
('WR (F), EB (F), KK (F)'),
('LB (F), WR (F), EB (F)'),
('WR (M), EB (F)'),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
('Arab (2), Byz (F), mix ()'),
('Arab (F), Rom (S), Byz (F)'),
('R/Byz (M), EB (), Mos ()'),
('Rom (S), EB (S)'),
('Wadi Raba (F), Rom (S)'),
('R/Byz (M), EB  (mix)'),
('Rom  (F), Per (S), EB (S)'),
(''),
('R/Byz (F), EB (F)'),
('R/Byz (F), EB (F), Arab  (S)'),
('R/Byz (F), EB (F)'),
('Rom (F), Byz (F), Arab  (2)'),
(''),
('IS (F), R/Byz (F), EB (F)'),
('R/Byz (M), EB (F), Pers (F)'),
('Neo (S), EB (F), R/Byz (F)'),
('EB (F), R/Byz (mix), IS (S)'),
('R/Byz (F), EB (F)'),
('R/Byz (M), Persian (S)'),
('R/Byz (M), EB (F), Hel (F)'),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
('R/Byz ()'),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
('Rom (M), Mix (F)'),
('Byz (M Mixed)'),
('Wadi Raba (F), Mixed ()'),
('EB (M)'),
('Neo (S)'),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
('Chal/Ghas(3)'),
('R/Byz  (M), Glaze Islam F (F), EB  (F)'),
('? ()'),
('WB (S), Per (S), R/Byz (S)'),
('EB  (M), Mix (Some)'),
('EB  (F), Wadi Raba (Few), Rom (S)'),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
('IA (F), R/Byz (), Med ()'),
('R/Byz (M)'),
('EB (), R/Byz ()'),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
('EB (F), Wadi Raba (F), Roman (S)'),
(', Wadi Raba (S), LB ()'),
('LB (), R/Byz (), Mix ()'),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
('EB: F/?: S'),
('EB: M/MB?: F'),
('EB: M/MB?: F'),
('EB: M/MB?: S'),
('Chal: F/EB: M'),
('EB: M/MB: F/Wadi R: S'),
('EB: F/Other: F'),
('EB: M/Wadi R: S'),
('EB: M'),
('EB: M/Late: F'),
('EB: unspecified'),
('EB: M/MB?: S'),
(''),
('Byz/Per/EB (unspecified quantity)'),
('EB: M/MB: F'),
('EB: M/MB: F(?)/Wadi R: S'),
('EB: M/Late: S/Chal: S'),
('EB: M'),
('EB: M/MB?: S'),
('EB: M/MB: F'),
('EB: M/Kh. Kerak (unspecified)'),
(''),
('EB: M/?: S'),
('EB: M'),
('EB: M'),
('EB: M/Chal ?: S'),
('EB: M only Early EB'),
('EB: M/Chal: F,'),
('EB: M'),
('EB: M'),
('EB: M  no late mixed'),
('EB: F/Chal: F/IA: F'),
('Kh. Kerak: S/EB: M'),
(''),
('Byz: S/EB: M'),
('IA: F/EB: F/Byz: S'),
('EB: F/Byz: F/MB: F'),
('MB: F/EB: M'),
('EB: M/MB: S'),
('EB-F-Ottoman-S'),
('By2-S-Chal-S'),
('EB-S-Early-M'),
('By2-S-Early-M'),
('EB-F-Chal-S'),
('EB-M-By2-S'),
('EB-M'),
('By2-F-?-S'),
('Wadi Rabbe-F-EB-F-By2-S'),
('EB-M-By2-S'),
(''),
('LB/M?-F-?-F'),
('Kh Kerak-F-EB-M'),
('EB-M-by2-1'),
('EB-M'),
('IA-S-EB?-1-?-M'),
('By2-S-EB-F'),
('By2-S-EB-M'),
('EB-F-By2-F-?-F'),
('EB-M'),
(''),
('EB-M'),
('EB-M'),
('EB-M'),
('EB-M'),
(''),
('Wadi Rabbe-S-EB-M'),
('EB-M'),
('EB-M-?-S'),
('EB-M'),
('EB-M-MB-F'),
('EB-M'),
('EB-M'),
('EB-M-Chal-F-Wadi Rabbe-F'),
('EB-M'),
(''),
('EB-M-By2-S'),
('EB-M'),
('EB-M-By2-S-?-S'),
('EB-M-Neo-S'),
('EB-M'),
('EB-M-By2-S'),
('EB-M'),
('EB-M-Wadi Rabbe-S'),
('EB-M-Later-F'),
('EB-M'),
('EB-M-?-S'),
('EB-M'),
('EB-M'),
('EB-M'),
('EB-M'),
('EB-M-?-S'),
('EB-M'),
('EB-M'),
('EB-M'),
('EB-M-R/By2-S'),
(''),
('EB-M-MB-F'),
('EB-M'),
('MB-F-?'),
('EB-M'),
(''),
('MB-F-EB-M'),
('R-EB-M-MB-?-F'),
('EB-M-MB?-F'),
('EB-M'),
('EB-M-Later-F(2)'),
('EB-M'),
('MB-M-?-F-EB-F'),
('By2-S-EB-F-later-F'),
('EB-M'),
('EB-M-later-S'),
('IA-S-EB-M'),
(''),
('EB-M'),
(''),
(''),
(''),
('mixed'),
('mixed/late'),
('EB-F MB-? '),
('Mixed-late '),
('Mixed-inc KKW '),
('EB-F, Poss Late-F. '),
('EB-ALL. '),
('Byz S. In North of square'),
('Byz F, Islamic S. In SE of Square'),
('Byz F, EB F. V. mixed. In North of square'),
('Isl S, WR S, EB F, Yarmukian & WR. In SE of square'),
('Roman/Byz F, WR F, WR mixed. In north of square'),
('Rom/Byz S, EB F-mixed. In SE of square'),
('Extreme SE Corner'),
('Mixed'),
('ll'),
('WR F, EB F, Later S'),
('Mixed'),
(''),
('Byz S, EB F, Mixed'),
('EB M, (EB1, EB3)'),
('EB M, Late S'),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
(''),
('EB: M'),
(''),
('?: F'),
('EB: M; lab taken for mudbrick'),
('EB: M'),
('MB: F/EB: F'),
('EB: M/possible MB: F'),
('EB: M/MB: F; lab taken for mudbrick'),
('EB: M/Late: S'),
('EB: M/MB: F; lab taken for mudbrick'),
(''),
('EB: M'),
('EB: M Wadi R: S'),
('EB: M'),
('EB: M'),
('EB: M'),
('EB: M/MB: F, grey burnished'),
('EB: M'),
('IA: S/EB: M/Late: S/ Kh. Kerak: unspecified'),
('EB: M/Wadi R: F'),
('EB: M/MB: S/Wadi R, Kh. Kerak'),
('EB: M; Wadi R: F'),
('EB: M; Wadi R: '),
('EB: M/IA: S/Byz: S/MB?: unspecified'),
('LB: F/Byz or Rom?: S/EB: M'),
('Byz: S/Yar: F'),
('Chal: S/?: M'),
('EB: M'),
('IA: S/Byz: S'),
('EB: M'),
('EB: M'),
('EB: M'),
('EB: M'),
('EB: M'),
('Kh. Kerak: F/MB?: F/EB: F'),
('EB: F/?: F'),
('Chal: S/EB: M'),
(''),
(''),
('Byz: S/EB: M'),
('EB: M'),
('MB: S/EB: M'),
('EB: M'),
('EB: M'),
('EB: M/Early?: F'),
('Mixed: EB: M/Byz: S. '),
('Mixed: M/ IA: S  (samaria ware)'),
('EB: M'),
('Mixed IA EB Byz'),
('EB: M'),
('IA: S/EB: M/Roman: S'),
('Byz: S/EB: F/IA: S'),
('Byz: S/EB: M'),
('EB: M/Byz: S/?: S'),
('EB: M/IA?: S'),
('EB: M/Per: S'),
('EB: M'),
('EB: M/late: S'),
('EB: M/MB?: F'),
('EB: M'),
(''),
('EB: M'),
('EB: M/late: F'),
('EB: M/late: S'),
('EB: M'),
('EB: M'),
('Byz: S'),
('EB: M'),
('EB: M'),
('EB M, YarI, YarII'),
('EB M, Roman s, IA1 F, taboon'),
('EB M, Byz F'),
('EB M, Roman s, IA IIB s; southern end; f'),
('EB M, Rom/Byz S, IA S'),
('EB M, BYZ F, late F'),
('EB M, Byz/Um F, Rom S'),
('EB M, Pers? 2, Rom? 1'),
('Rom/Byz 5, EB 6, Late 3, IA 1'),
('late Med/early Ottoman 3, IA2AB 1, 12-13'),
('EB 1, IA 2, Unk 1'),
(''),
('Rom 1, Abbassid 1, 12-13th C. 3, IA 1 (S'),
('12-13th C. 4, MB bowl 1, Cook ware 1, po'),
('ETC S, IA 2, EB S, LB base rim S, Ottoma'),
('12-13th C. F, ETC S, EB F, KKW even mix '),
('EB M, KKW 10, early Rom 1, MB? 1, Byz/Ro'),
('Med 12/13th 3, EB KKW 4, MB 1, IA 1 (Top'),
(''),
(''),
('EB M, Rom S'),
(''),
('EB M, Med S'),
('EB M, Ot F, Byz/Um F'),
('EB M, Byz/Um F, Rom S'),
('EB M, Hand-made Med S, Rom F, Fahanania '),
('EB M, early Rom F, late IA S'),
('EB M'),
('EB M, IA F, Rom F'),
('EB M, IA F'),
('EB M, IAB, Roman'),
('EB, IrAB, Medieval'),
('EB M, MB F, LB'),
('EB M, MB S, IA F'),
('?'),
('EB M, Rom/Byz F'),
('no sherds'),
('EB S, Ott S (jug)'),
(''),
('EB M, Chal F, Ott F, IA F, mixed'),
('EB M, Per F'),
('mixed'),
('EB M, Rom S'),
('Med Glaze & Graffiti F, Rom/Byz F, IR F'),
('EB M, Hell S'),
('EB M, Rom F, Per S, Hell S'),
('Chal F, EB M, Rom/Byz F, IA S'),
('EB All'),
('EB F, MB S, Med F?'),
('EB M, Rom F, late Med F'),
('EB All'),
('EB M, Chal S, IA F'),
('Unclear'),
('MB S, EB S, ER S; Tel Yehud ware'),
('EB M, Roman F, Late F'),
('EB M, Roman F, Med F'),
('EB 1 A All'),
('EB M; GBW'),
('EB M, KKW S, IR F, Hel S, Rom F'),
('EB M, IR IIAB-III F, KKW S, Rom F'),
('EB M, Rom F, LN S'),
('EB M, Rom F, UnKn 2, Iron S'),
('PN M'),
(''),
('EB M, IAII AB 2 (rims), Byz 2, Roman 1'),
('EB 1 (rim?), Sam 1'),
('Handmade common ware 5, KKW 1, Rom 1'),
('undiagnosed'),
('EB F, late S'),
('KKW F, EB F, Rom S'),
('EB M, Sam S, Chalc S, KKW S, IA S, late '),
('EB(?) S, Mixed 4'),
('TS 1, Ott F, EB M; mixed'),
('EB M'),
('mixed'),
('Rom Main 5, EB F'),
(''),
('EB M, Roman S'),
('EB M, KKW F, Byz S Miniature vessel, Jet'),
('EB M, Med (9th C) 3, IA S'),
('EB M, 2 poss. Later handles'),
('Late F, KKW F'),
('Byz-F, WG-S, EB-M, Mixed + KKW-S'),
('EB-M, Rom-F'),
('EB-M, Rom/Byz-F, LB?-S'),
('Chal-S, EB-M, Byz-F'),
('EB-F, Byz-F, Rom-F, Mixed'),
('WB-F, WR-F, EB-F, Byz-F, Mixed'),
(' no pot-Area not worked on this day'),
('EB M, OH F, Chal S'),
('EB M, LN S, Rom F, IA S; mixed'),
('EB M (60%), Rom S, Late? S'),
('EB F, Rom F'),
('EB M, Rom/Byz F, Chal S, L S'),
('EB M, Rom F'),
('EB M, Rom F, Byz F'),
('EB M, Rom F, Byz some'),
('ETC F, KKW F, Unknown Late rim 1, rest m'),
('EB, Rom, Byz, KKW, many sherds mixed'),
('EB all'),
('EB M, N F, Rom F, L F'),
('EB M, IA S, Late F'),
('EB M, L? S'),
('EB M, Neo F, Roman F, Byz F, LB(?) S, IA'),
('EB M, Late F'),
('EB, Rom; mixed'),
('EB, Byz, Med; mixed'),
('EB M, Chal S, IA S, Rom S, ? F'),
('EB M, Byz F, Rom S, LN S'),
('EB M, poss MB(?) S, Rom F, late(?) F'),
('EB M, Rom F, Med F, Chal S'),
('EB M, LN, S Byz F'),
('EB F, Byz F'),
('EB main, R Few'),
('pottery bucket missing?'),
('EB M, Rom F'),
('EB M, Byz/Um F'),
('EB M'),
('EB M, Chal S, Rom F'),
('EB M, Roman F; Cypro-Phoe?'),
('Mixed Chal-Rom'),
('EB F, Late S'),
('EB all [Rom S]'),
('EB all'),
(' sherds'),
('Completely mixed from early to late'),
('EB-M, R-S,'),
('LN-F, B-F'),
('EB-M'),
('EB-M'),
('EB-M, L-S'),
('EB all'),
('EB-M, L-2'),
('EB-M, L-2'),
('EB-M, Byz-S'),
('EB-M, Byz-F'),
('EB-M, LN-S, Rom-F'),
('EB-All'),
('EB'),
('EB-M, ?-F (mystery profile)'),
('bucket missing?'),
('LN-1, EB-M, Rom-S'),
(''),
('EB-F, Late-F, Mixed'),
('EB-M, Mixed-all periods up to Roman'),
('EB-M, Mixed-all periods up to Roman'),
(''),
('EB-M, Mixed-all periods up to Roman'),
('EB-M, Mixed-all periods up to Roman'),
('EB-m, Rom/Byz-F'),
('EB-Rom, hight volume of sherds'),
('EB-Rom'),
('EB-M, Late-F, KKW-S'),
('(abraded)'),
('Chal/EB all?'),
('EB-All'),
(''),
('EB-M'),
(''),
('EB but mixed with later pot'),
(''),
(''),
(''),
('EB-M'),
('EB-M'),
('EB-M, plus 2 reworked sherds'),
('EB-M, plus CBM'),
('EB-M'),
(' EB-M'),
(' EB-M'),
(' EB-M'),
('Missing as of 20/6'),
(' EB-M'),
(''),
('EB all'),
('EB M, LN-S, Byz-S'),
('Eb-M'),
('EB-M, LN-S'),
('EB-M, Late-F'),
('EB-M, Lare?-F'),
('EB-M, Byz-S'),
('EB-M, Incl-Late'),
('Mixed-EB to Byz'),
('Mixed'),
('EB-F, Rom-F'),
('EB-F, Rom-F'),
('EB-M'),
('Late?'),
(NULL),
('EB (s), Otto (s)'),
('EB (f), MB (s), Otto (f)'),
(NULL),
(NULL),
(NULL),
('Bronze (s)'),
('Chal (f), EB? (f), Isl (f)'),
('MB (s), EB (f), Isl'),
('EB (f), Medieval'),
('Crusader/Mamluk, EB, Roman/Byz'),
('EB (s), MB (s)'),
(NULL),
(NULL),
('EB (f), Byz/Rome (f)'),
(NULL),
(NULL),
(NULL),
('EB (f)'),
(NULL),
(NULL),
(NULL),
('EB, Med, WR'),
('Neo, EB, Byz'),
('KKW, EB'),
(NULL),
('Neo, EB, Byz, Hel'),
('Chal/EB, Byz, KKW'),
('Neo, EB, Rom/Byz'),
('Neo, Pers'),
('EB (main), mix'),
('EB (main)'),
('Neo - Persian'),
('Neo - Persian'),
('L. Neo, Isl'),
('L. Neo, R.Byz'),
(NULL),
('L. Neo, R.Byz, Pers'),
('L. Neo, R.Byz (1)'),
('L.Neo, Pers'),
('EB. Pers'),
('EB, Pers'),
('EB, Pers'),
('EB I, Pers'),
('Early'),
('EB (m), LB/Iron, WR'),
(NULL),
('EB (f), Medieval (f)'),
('WR (m)'),
('Wr (f), MB (s), EB'),
('EB, WR, Iron?'),
(NULL),
('WR, Med glazed'),
('WR, EB, Med'),
(NULL),
('WR, EB, Roman'),
('WR, Roman'),
('WR, EB, Ottoman'),
('EB'),
('WR, Roman'),
(NULL),
('WR, Roman'),
('WR (f), EB (f), Med (s)'),
('EB'),
('WR, KKW, Rom'),
('Pers (1)'),
('MB (s), EB (m), WR? (s)'),
('WR (f), EB (s), medieval'),
('Rom/Byz (s), EB (m)'),
(NULL),
('Crusader, Persian, EB'),
('WR, EB (m), MB'),
('Neo to Byz mixed'),
(NULL),
(NULL),
('Neo, EB, MB, LB, Rom (1)'),
('L. Neo, Pers, Byz (1).'),
('EB (main), Mix'),
('EB, Wadi R, Pers'),
('EB, MB, Persian'),
('WR (1), EB (5+), MB (?), Byz (1)'),
('EB'),
('Neo/WR (2), EB (1), KK (1), Pers (1), late'),
('EB (m), WR (f)'),
('WR (s), EB (f)'),
('L. Neo, Byz'),
(NULL),
('EB, LB, Byz'),
('Neo, EB, Pers, Rom'),
(''),
('EB, Grk (Helle) (1), Byz'),
('WR EB, IR'),
('EB, Wadi R'),
('EB, Neolithic, Iron Age'),
('EB, Iron Age'),
('EB, Roman, Persian'),
('EB, Persian'),
('EB, Wadi Raba, Persian'),
('Neo, EB, Iron, Roman, LB'),
('EB'),
('EB, Pers'),
('EB, Pers'),
(NULL),
('LB, WR, KK, EB'),
('Neo (1), Iron (1)'),
('EB'),
('EB (f)'),
(NULL),
(NULL),
(NULL),
('EB (f), LB/IR? (s) Medieval (f)'),
('EB'),
('MB, Rom/Byz, EB'),
('EB'),
(NULL),
('Early (s)'),
(NULL),
(NULL),
('EB (s)'),
(NULL),
(NULL),
(NULL),
('WR. Iron, Pers'),
('EB, MB mix'),
('Medieval (s)'),
(NULL),
(NULL),
('EB, Rom'),
('EB'),
('EB'),
('EB, Pers, Med?'),
('EB, Wadi R, Iron Age'),
('EB'),
('Neolithic, EB, Persian'),
('Persian'),
('Neo, EB, MB, Pers'),
('EB, Neo (1), Pers, Rom'),
('EB, Pers, Rom'),
('Neo, EB, Pers'),
(NULL),
('EB, Pers'),
(NULL),
('Neo, MB, EB, possibly Rom/Byz'),
('Neo, EB, Pers'),
('EB, Byzantine'),
('EB (some), Byz (main)'),
('WR, EB, Rom'),
('KKW, MB, EB, Iron'),
(NULL),
('EB (m)'),
(NULL),
('EB, MB?'),
('EB, Pers'),
('WR. EB (main)'),
('EB (f), WR (f)'),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
('EB, WR'),
('EB (f), Byz (f), Medieval (f)'),
('EB (m)'),
('NL (f), EB (f)'),
(NULL),
(NULL),
('MB (m), WR? (s), medieval (f)'),
('EB (f), MB/LB (s)'),
(NULL),
('EB, Iron'),
('WR, EB, KK, LB?, Iron?'),
('EB, WR (1), Pers'),
('EB, MB?, Iron?'),
('EB, Byz'),
('EB, KKW, Rom?'),
('EB, Byz'),
('Neo, Bronze, Pers'),
('EB?, WR?, Roman, Byz'),
('EB-P, Myce (1)'),
('EB (m), WR (f), Medieval'),
('EB (m)'),
('EB (f)'),
(NULL),
('EB (f), Neol(?), C.E.'),
('EB (f), Rom/Byz (F), village (s)'),
('EB (f), WR (f), Rom/Byz (f)'),
(NULL),
(NULL),
('medieval (f)'),
('EB (m), medieval (f)'),
(NULL),
('Neo - Rom'),
('Unclear?'),
('Neo, EB, Iron'),
(NULL),
('EB, Iron, Pers'),
(NULL),
(NULL),
('EBI'),
('WR?, EB?, Persian'),
('Neo, Pers'),
('WR, Pers'),
('EB'),
(NULL),
(NULL),
(NULL),
('EB - medieval'),
('EB + sth(?) later'),
('EB + sth(?) later'),
('LB, EB, Cypriot milk bowl  fragment'),
('EB, Byzantine'),
('LB'),
('EB, ?'),
('EB, Persian'),
('EB'),
('WR, EB, Byz Rom?'),
('EB I A (gray burnished), We (several), Rom/Byz'),
('EB, Roman?'),
('EB IA (gray burnished), KK, Iron?'),
('EB'),
('EB II, MB? WR?'),
('EB, Iron'),
('Neo, EB, WR, MB, gray burnished, Roman'),
(NULL),
('EB (m), later (mix)'),
('EB'),
('EB, LB'),
('Wadi Raba, Iron'),
('EB, MB'),
('Neo WR (few), EB (main), Iron (few)'),
('EB, unknown'),
('unknown'),
('EB, MB, Pers'),
('EB, unknown'),
('EB, Iron, Pers'),
('WR, EB, Byz'),
(NULL),
('MB, medieval'),
('WR (f), EB (I), MB?, medieval'),
('WR (s), EB (f), medieval (f), Byz (1)'),
(NULL),
('EB (s)'),
('WR (s), EB (f), C.E.'),
('EB (f), WR (f), Per/Byz? (s)'),
('WR? (f), EB (f), Rom/Byz (f)'),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
('EB'),
('unclear'),
('gaza ware'),
(NULL),
('EB'),
('EB (f), Byz (f), medieval (m)'),
('EB (f), Rom/Byz (f)'),
('EB (f), MB? (s), med (s)'),
('Neo (s), EB, med'),
('EB (f), med?'),
('EB, MB or LB'),
('EB (m), WR?'),
('EB (m)'),
('WR, EB, IR'),
('EB'),
('EB, Persian'),
('EB, some later'),
('WR, EB'),
('EB, Pers'),
('WR, EB, Byz'),
('EB'),
(NULL),
('WR EB, Pers'),
('Iron, EB, early'),
(NULL),
('WR. EB. IR, Gaza'),
('WR? (f), EB (m), MB (f), med'),
('WR to Persian'),
('EB, IR, Rom'),
(NULL),
('WR, EB, Pers'),
('WR, EB, Rom'),
('WR, EB, Iron'),
(''),
('KKW, EB, Pers'),
('EB, MB'),
('EB, Persian, KK, Byz, Roman, WR'),
('Mix'),
('Neo, EB, Iron, Byz'),
('WR, EB, Iron(?)'),
('Neo - Byz mix with WR'),
('WR, EB, Pers, Rom?'),
('WR, EB, MB, Pers'),
('EB'),
('unclear'),
('Medieval (f), EB'),
('EB? Roman?, Medieval'),
('EB (f), Roman (f), medieval'),
('WR?, EB, Rom/Byz (s), post-Iron'),
('post-Iron'),
('EB (m), WR?, Persian (s)'),
('EB, Rom/By, med'),
('EB, med'),
('EB (f), med'),
('EB (f), KKW, MB'),
('EB (f), med'),
(NULL),
('EB (m), WR?, med, Pers (s)'),
('EB (m), MB (s)'),
('WR, Iron, Pers'),
('WR, EB, Pers'),
('WR, EB, LB, Pers'),
(NULL),
('WR, EB, MB, Byz'),
(''),
('EB to Pers, mixed'),
('EB, Iron'),
('EB, Iron'),
('WR, EB (s)'),
('EB (m)'),
('EB, MB, Helle, Rom'),
('WR EB, Pers'),
('EB'),
('EB, MB (s), Rom Byz'),
('EB, Rom/Byz, C.E.'),
('WR (f), EB (m), MB (1)'),
('EB'),
('WR, med'),
('Neo-EB, Med'),
('WR?, EB, MB, Byz/Rom, medieva'),
('EB'),
(NULL),
('EB, WR, KK, Persian'),
(NULL),
('WR, EB, later'),
('EB (m), MB, Neo?, WR'),
('EB'),
('EB (mix), Iron?'),
('EB, Pers'),
('WR, EB, Neo?'),
('WR, EB'),
('EB, Iron, MB'),
(NULL),
('EB (f), MB (f)'),
('WR, EB, Med'),
('EB'),
('EB, MB, med'),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
('Rom/Byz'),
('EB, Byz'),
('EB, Iron?'),
('EB, ?'),
(NULL),
('WR (s), EB (f), Iron?'),
(NULL),
('WR (f), EB, Rom/Byz, medieval'),
(NULL),
(NULL),
('EB, WR? (s)'),
('EB, Rom/Byz, med'),
('EB (f), MB (f), med (f)'),
('EB (m), med (m)'),
('EB'),
('EB'),
('EB (m)'),
('EB (m), MB (f), Persian (s)'),
('EB, late'),
('EB, LB?, Isl/Med'),
('EB, Pers, Byz'),
(NULL),
('EB'),
('WR, Rom'),
('WR EB'),
('WR, EB,Rom'),
('EB, Rom?, Byz'),
(NULL),
('EB, ?'),
('Rom/Byz(M), Early(S) - '),
('Rom/Byz(M) - Very small amount (early piece without feature)'),
('Early (M), Byz(S) - Early unidentifiable pieces'),
('Rom/Byz(M), Early(F) - Hard to ID early pieces'),
('IA (M), Byz(S) - IA to Byz, nothing distinctive'),
(' '),
(' no pottery'),
(' '),
(' '),
(' '),
(' '),
(' '),
(' '),
(' '),
(' '),
(' '),
(' '),
(' '),
(' '),
(' Tomb'),
(' Oil'),
(' Oil'),
(' '),
(' Oil'),
(' '),
(' Mixed'),
('Gaza ware Mix/nothing'),
('Wadi Raba(2), Rom/Byz(2) - Mixed'),
('IB(), Chalc?() - Early'),
('Byz/Rom(2/3), Wadi Raba(f), EB(f) -  '),
('Medieval(3), Wadi Raba(3), MB(1) -  '),
('Medieval(1), EB(1), Byz(1) -  Storage vessel medieval? Village?  1 unknown late'),
('Persian Mortar?  Wash in pit'),
('Medieval(M) - Restoration medieval'),
('EB(), Medieval(M), MB(1) -  Material NW of wall Crusader'),
('Medieval(M) - Byz to Medieval'),
('Medieval(M) - Byz to Medieval'),
('EB(), Medieval() - Restoration medieval'),
('Kirbet Kerek(), WR() - '),
('Mixed(M), Calchlithic(S) - Village ware; 1 medieval'),
('WR(F), EB(M), Gaza ware(F) -  WR to Gaza ware'),
('WR(M), mixed() - Mixed; nothing modern'),
(' EB to Byz'),
('Mixed(M) - WR, EB, Rom/Byz, Gaza, Medieval'),
('EB(S), Medieval(F), Roman (S) -  W side of square'),
('EB(S) - '),
('Medieval(), MB(), Wadi Raba() -  Restoration medieval'),
('Medieval(), Kirbet Kerek() - Medieval with some early'),
('WR(S) - '),
(' '),
(' '),
('Medieval(S), MB(S) - WR to late, MB, KK'),
('Mixed '),
('EB(S), R (S) - EB to Roman'),
(' late'),
(' late'),
(' '),
(' surface with nothing to keep'),
('Medieval '),
(' Late Roman to Byz'),
(' Some pieces lost when bucket was blown over. '),
(' Rom-Byz'),
('Mixed(M) - WR to MB (EB)'),
('Mixed(M), MB (S) - MB & Roman'),
(' Mixed'),
('Medieval(S LB) - Village ware?  EB to Medieval'),
(' '),
(' WR to Rome-Byz, Village?'),
(' '),
(' '),
('Mixed(M) - WR to Roman'),
(' '),
(' WR to Rome-Byz'),
('MB(M) - Only MB'),
('Crusader WR to Crusader'),
(' '),
(' WR to Medieval'),
(' EB to Rom/Byz'),
('WR '),
(' No pottery'),
(' WR to Medieval'),
(' '),
(' '),
(' '),
(' WR to Medieval'),
(' WR to Rom'),
(' EB'),
(' Unidentifiable'),
(' Unidentifiable'),
('WR to Medieval Crusaer bowl'),
(' Mixed'),
('EB to Medieval One sherd to Restoration'),
(' Medieval; 1 sherd'),
(' Medieval; 2 sherds'),
('WR(), EB() - Some later; iron?'),
('WR(), EB(), Rom/Byz() -  Later'),
('WR(), Rom/Byz() - '),
('EB Mixed'),
('EB EB - medieval'),
('WR(), Crusader() - One sherd to Restoration'),
(' unidentified'),
('IA (F), KK() - early'),
('Mixed(M), WR(few), Byz() -  topsoil clearing'),
('EB(all) - topsoil clearing'),
('EB(), Rom(few) - topsoil'),
('EB(all) - topsoil'),
(' Mixed wadi rabba / persian'),
('EB(some) - EB - mixed'),
('EB(M), KK(S), Neo(S) -  All early'),
('EB(M), Med/Byz(few) - '),
('Persia(S ) - Mixed'),
('WR(), Roman() - Mixed'),
(' Mixed WR - Med'),
('WR(some), EB (some), Pers(2) -  WR-mix'),
(' '),
('EB(1), MB(1) - all early'),
(' mixed'),
(' mixed'),
(' mixed EB - Persian'),
('EWR(F), Byz(few) - '),
(' mixed WR-Byz'),
('EB(), WR() - all early, maybe some Chalcolithic'),
('WR(), EB(), Rom() -  WR to Roman'),
('WR(), (), Medi() -  WR to Islamic/medieval'),
('WR(), (), Medi() -  WE to modern'),
('EB '),
('WR(), EB(), Ottoman() -  mixed'),
(' mixed'),
('WR(), EB(), Rom(?)() -  WR - Rom(?)'),
('EB(Some), Byz(1) - WR - EB, maybe 1 late, some Byz'),
('WR(), EB(), IA() -  mixed'),
(' EB - MB ? - mixed'),
('WR(), Byz(F) - mixed'),
('WR(), EB() - '),
('Persian(), Hel(), WR() -  mixed'),
('Rom?(), WR(), IA() -  mixed'),
(' mixed WR - Persian/Byzantine?'),
(' mixed WR - Roman'),
('WR(), EB() - mixed WR - EB'),
(' mixed WR - Byzantine'),
(' mixed WR - Roman'),
('WR(few), EB(few) - '),
('LI CM2(few), EB(main) - '),
('EB(main), IA(few), Pers(few) -  chalcolithic sole, WR sole'),
('WR(main), EB(main) - '),
(' '),
(' bucket was stolen'),
('WR(), Persian() - Mixed/Eroded'),
('EB to Rom/Byz Mixed/Eroded'),
('WR to MB/LB Mixed/Eroded'),
('WR to Iron '),
('WR to EB Early tiny/eroded'),
('WR(), EB() - Tiny/eroded'),
('EB to Medieval Tiny/eroded'),
('WR to Rom/Byz '),
('WR to Medieval Mixed'),
(NULL),
(NULL),
(' Unidentifiable/Mixed'),
('WR to EB to ??? Wheelmade '),
('WR to Rom/Byz '),
('WR to EB to Byz Mixed'),
('WR to Ottoman Mixed'),
('WR to Poss Neo Whiteware to EB Tiny/eroded'),
('EB to Byz Mixed  Tiny, eroded'),
('WR to Rom/Byz Mixed'),
(' Mixed'),
(' KK'),
(' EB (mostly), WR, Rom sole'),
(' WR, KK, MB, Iron'),
(' Later, EB'),
(' Early'),
(' WR - Bronze mixed'),
(' Older?  WR?'),
(' WR - Persian - Rom/Byz'),
(' WR - EB - Byz'),
(' WR MB Byz'),
(' WR KK Rom/Byz'),
(' WR EB KK Persian'),
(' '),
(' WR EB Persian'),
(' WR MB Rom'),
(' '),
('WR WR   Ottoman  Mid'),
('WR to ?? Mixed, small'),
('WR to EB to Byz Mixed '),
('EB to ?? Nothing late'),
('EB to ?? \"'),
('EB to ?? '),
('WR to ?? Mixed, small'),
('WR(few), Persian(sole) - south corner'),
('EB (M ), MB(M ), Byz(S) -  WR F'),
('MB(few), WR(few) - '),
('MB(), EB(), WR() -  Possibly late'),
(' WR  - Undatable'),
(' Very tiny pieces'),
(' '),
(' '),
('WR(), EB() - Mixed often unidentifiable'),
(' Mixed EB - Byz'),
(' Mixed WR - Byz'),
('WR(), EB(), Iron() -  Mixed WR - Byz'),
('WR(), (), Rom() -  Mixed WR - Roman'),
('WR(), EB() - Mixed WR - Unidentifiable later'),
('WR(), MB(), Iron() -  Do not use; from 161'),
('WR(), KK() - Mixed WR - EB'),
(' EB, WR, KK'),
(' undatable'),
(' EB, WR, Byz'),
('WR(), MB(), LB?() -  WR - Rom/Byz mix'),
(' EB, MB'),
(' KK, MB, Persian = latest'),
('EB(), Iron() - Pile. WR - Iron'),
('EB South of pile'),
('WR(), EB(), Pers() -  Pile, WR - Persian'),
('WR(), Pers(), MB() -  North of pile, WR - Persian'),
('WR to Iron  to Crusader Mixed'),
('WR(to ), Byz() - Mixed'),
('Maybe WR(), EB() - Nothing late'),
('WR(), MB(), Pers() -  WR - Persian'),
('EB(some), Iron(some) - Later than surrounding loci'),
(' WR, EB, MB'),
(' MB, Persian, Iron'),
(' EB, MBII, Byz'),
(' '),
('Megera?(Sole) - WR - Byz'),
('WR(), MB(1) - WR - Iron (Medieval? 1)'),
('WR(1), Iron(), Ottoman?() -  WR - Ottoman(?)'),
('WR(), EB(), Bronze Age() -  WR - Bronze? MB/LB?'),
('WR(), EB() - WR - EB mix'),
('WR(), EB() - from layer down to mudbrick'),
(' from above stones & mudbrick, entire N-half of square'),
(' Mixed WR - Byz'),
('EB(), WR(), Byz() -  Mixed WR - Byz'),
('EB(), Iron() - Mixed EB - Iron'),
(' EB, WR, Byz'),
(' EB, IA?, Byz'),
(' EB, Neo, WR, possible Rom'),
(' EB, WR, MB'),
(' EB all'),
(' Deposit clearing'),
(' WR to Roman'),
(' WR -- Byz'),
(' Chal, WR, MB , Byz'),
(' WR, EB, MB'),
(' Abydoss'),
(' '),
(' '),
(' N of W002; look w/ L122'),
(' '),
(' '),
(' EB, MB? Pit sectioning'),
(' Unclear date; E half; Pit bottom?'),
(' WR - Persian mixed'),
(' EB, Persian?'),
(' IA, KK, breadtray frag (WR-IA); includes sectioning'),
(' EB, Byz'),
('KK EB to IA(?)'),
(' WR to IA(?)'),
('WR -- Byz '),
('WR -- EB No late'),
('WR -- EB '),
('WR --EB --MB '),
(' '),
(' '),
(' Unidentifiable/Mixed'),
(' Unidentifiable/Mixed'),
('MB Later than EB. 1st flat lying PT, 2nd handle under rocks'),
('Later than EB'),
('WR(), EB(), MB() -  WR - MB'),
('WR - EB No late'),
(' Mixed'),
('Rom (few), KK(), WR() -  '),
('MB(), EB(), Mix() -  KK, WR, Per, Rom'),
('EB(M), WR() - MB, IA(?)'),
('WR(), EB(), MB() -  IA(?)'),
('WR WR to MB'),
(' Mixed WR - Byz'),
('WR(), Greek(1) - Mixed WR - Greek/Rom'),
('Iron(), WR() - Mixed WR - Iron'),
('WR(Cyp), Metallic(LL), EB(Byz) -  Mixed WR - Byz'),
(' Mixed WR - Roman'),
('Everything Mixed WR - Byz'),
('WR(), EB() - '),
('WR(), MB?(), Persian() -  Mixed WR - Persian'),
(' Mixed WR - Roman'),
(' WR, EB, MB(S), Perian (S)'),
(' WR, EB'),
(' EB; Pieces taken for small restoration'),
(' W only; EB (early)'),
(' '),
(' W half only; WR,EB'),
(' NW rocks; WR-MB?'),
(' WR - Roman'),
(' WR - MB'),
(' WR - MB'),
(' WR - MB'),
(' Mixed, WR - ? Late unknown'),
('WR(), Roman?() - WR - Persian'),
('WR(EB), Byz() - WR - Byz'),
('WR(EB), Iron(MB), Persian (large)() -  WR - Persian'),
('WR(S), MB(S) - '),
(' EB all'),
('WR -- Byz '),
('WR -- Byz '),
(' Mixed'),
('WR -- Byz '),
(' Same'),
('WR(), EB(), MB?() -  '),
('Neo/Chalc?(), EB(), MB?() -  '),
(' Unidentifiable'),
('EB -- Byz '),
('EB(), Pers() - EB, Pers mix'),
('EB(), MB(), Roman() -  EB, MB, Roman'),
('WR(), MB(), (unclear)() -  '),
(' WR, possible MB'),
(' '),
(' '),
(' WR to Rom(?)'),
('EB(M), WR(?), Byz(S?) -  '),
('WR(), EB(), Mixed() -  WR - MB(?)'),
('WR(), EB(), MB() -  WR - MB(?)'),
('EB(), WR() - '),
(' '),
(' '),
(' '),
(' '),
(' '),
(' '),
('Pers(), MB(), WR/EB(), KK?IA? -  WR - Pers'),
(' '),
(' '),
(' Mixed WR - Roman'),
(' Mixed WR - Persian'),
(' '),
(' '),
(' '),
(' '),
(' '),
(' '),
(' '),
(' '),
(' '),
('EB(), MB?(), Rom?() -  '),
('WR(), Iron?() - Mixed WR - Iron?'),
('Rom(F), EB(F) - EB - Roman'),
('EB -- MB '),
(' Mixed WR - Persian'),
(' Mixed WR - Roman'),
(' Mixed WR - Persian'),
('WR(), EB(), MB(F) -  WR - Rom/Byz(?)'),
(' One EB piece'),
(' '),
(' '),
(' '),
(' WR, EB, MB, Iron, Persian'),
(' WR, EB, MB, Iron(?), Persian'),
(' WR, EB, MB, Iron(?), Persian'),
(' WR, EB, MB, Persian; 3 sherds to Restoration'),
(' EB, MB, Persian, Roman(?)'),
(' WR, EB, IB(?), Roman(?)'),
(' '),
(' EB, Persian'),
(' WR, EB, MB, Persian, Rom/Byz, Hellenistic(?)'),
(' WR, EB, Roman'),
('Wadi Raba, EB'),
('Wadi Raba, EB, MB?, Iron Age'),
('Wadi Raba to Rom/Byz'),
(NULL),
(NULL),
('KK (1), WR (F), some late'),
('KKW (S), MB (F)'),
('WR (F), EB3 (F)'),
('EB, LB, Persian, Wadi Raba'),
('KKW, LB, EB, Wadi Raba, Persian, Roman'),
(NULL),
('EB'),
('KKW (F), EB3 (F), Iron (F), Persian (F)'),
('KKW (S), WR (F)'),
('Persian, WR, MB (S), LB (F), KKW (F)'),
('Persian (S), KKW (S)'),
('WR to Persian'),
('EB, Persian, MB'),
('MB/LB (1), WR (1), EB (1)'),
(NULL),
('WR (F), EB III (F)'),
('EB (I?)'),
(NULL),
('EB, MB?'),
(NULL),
('Wadi Raba to MB?'),
('Mixed'),
('EB'),
(NULL),
('EB to medieval.  Possible resoration piece of Mamluk'),
('EB (M), MB (some), crusader (1)'),
('EB to Rom/Byz'),
(NULL),
('Wadi Raba to EB'),
('EB, Neolithic, IA, Persian'),
('Wadi Raba, Iron Age'),
('Wadi Raba'),
('EB (F), IA (S)?'),
('WR (F), KK (F)'),
(NULL),
('EB (M)'),
('WR, EB III, MB'),
('KK (F), MB (F), WR (F)'),
('KK (1)'),
('EB (F), KK (F), WR (F), Byz?'),
('EB(M)'),
('EB'),
('LB, WR, KKW'),
('EB (M), MB (S)'),
('EB, WR, Persian'),
('KK (F), EB (F), LB (1), Persian (1)'),
(NULL),
(NULL),
('EB (KKW), LB/IA?'),
(NULL),
(NULL),
('EB (some), MB (some), Rom/Byz (1)'),
('EB (M), MB (F)'),
('WR (some), EB (some)'),
('MB, Rom/Byz'),
('EB (some), MB (some) ,Rom/Byz (few), MB (few).'),
('EB (M)'),
(NULL),
(NULL),
('EB and possible Wadi Raba'),
('WR (F), EB (F), MB (F).'),
('EB'),
('EB (all)'),
('EB'),
('WR (F), EB II (F), KK (F), 1 late'),
('EB, early'),
('1 late'),
('WR, EB'),
('WR to Byz'),
(NULL),
('WR, KK, EB'),
('KKW, EB, Persian, MB, late'),
('KKW, WR, Byz'),
('WR, MB?'),
('Wadi Raba, EB'),
('Wadi Raba, EB'),
('Iron Age, late'),
('LB, WR, Rom, Persian'),
('WR, Ro(?), MB(F)'),
('EB (M), WR'),
('WR (F), EB (F), late, Persian'),
('KK (F), WR (F), late (F)'),
('KK, WR, EB'),
('EB (M), MB(?)'),
('EB (F), MB (F), IA? (S?)'),
(NULL),
('EB'),
('EB'),
('EB'),
('EB, Iron Age'),
(NULL),
(NULL),
('EB (M), two late sherds'),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
('(no periods entered on PT sheet)'),
(NULL),
('EB (M)'),
('EB (M), MB (F), Rom (1)'),
('MB, LB?, EB'),
(NULL),
('EB, Persian, MB too'),
('EB, Greek (Attic)'),
('EB'),
('EB to Rom/Byz'),
('Wadi Raba, late'),
('WR, EB, KKW, Byz/Rom sherds mix'),
('EB, LB/Iron? Mix'),
(NULL),
(NULL),
('EB, Iron Age, some late'),
('IA, EB'),
('EB, Persian'),
('EB, Persian, Roman'),
('EB --> Persian , Rom/Byz'),
('EB --> Iron --> Persian'),
('EB, Wadi Raba'),
('EB, MB'),
('MB'),
('Mix'),
('WR - ?'),
('EB ---> early'),
('KK, EB'),
(NULL),
(NULL),
(NULL),
('EB (M), Rom/Byz (sole)'),
(NULL),
(NULL),
('EB (M), MB (F)'),
(NULL),
('Kirbet Kerak (1)'),
(NULL),
(NULL),
(NULL),
(''),
(NULL),
(NULL),
(NULL),
('EB, Wadi Raba, Cypriot, Persian'),
('Wadi Raba ---> Persian'),
('EB ---> Persian'),
('KK, Iron, Roman'),
('EB'),
('LB, Persian'),
('KK, WR, Iron, Persian'),
(NULL),
(NULL),
(NULL),
('EB, MB, late'),
('KK, WR, EB'),
('KKW -----> Per-Rom-Byz'),
('EB (F), WR (F)'),
('WR, LB'),
('EB (F), WR (1?)'),
('EB'),
('EB'),
('EB I'),
('EB I'),
('EB, MB(?), some late. Mix'),
('EB I(A)'),
('EB, WR (1)'),
('EB, MB'),
('EB ---> Persian'),
(NULL),
(NULL),
('EB I'),
('EB I'),
(NULL),
(NULL),
(NULL),
('EB'),
('WR (few), EB (some)'),
(NULL),
('WR --->'),
('WR, Pers'),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
('WR (some), EB (few)'),
('WR (few), EB (some)'),
('WR, EB'),
('EB (some), WR (few)'),
(NULL),
('EB (some), KK, late (1)'),
('WR, EB'),
('Persian'),
('WR, IA, Pers'),
('WR, Cypriot, Persian'),
('KK, WR, Pers'),
('WR, EB, later'),
('EB --> possibly Persian'),
('LB, mostly late'),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
('WR, EB'),
('EB, 1 grey burnished'),
('WR (some), EB (few)'),
('Mixed'),
('Mixed'),
('WR, EB, later?'),
(NULL),
('WR, EB, Persian'),
('WR, EB, KK, MB'),
('WR, EB I'),
('EB,LB, Hel'),
('EB (S)'),
(NULL),
('EB, Persian, Medieval'),
(NULL),
('Wadi Raba?  MB?'),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
('Wadi Raba, Late, Greek'),
('KK, EB ---> Byz'),
('KK, EB.  Roman'),
('WR, EB'),
('Wadi Rabah, KK, EB I - III, Roman, Byz'),
('EB I'),
('KK, EB, WR'),
('EB I, late Bronze'),
('EB I, WR?'),
('EB'),
('EB'),
(NULL),
(NULL),
('WR, IA'),
('EB'),
('WR, EB'),
('Persian'),
('EB, Persian'),
('EB, MB? Late'),
('Wadi Rabah ----> Bizantine'),
('EB'),
('WR, EB, KK, I'),
(NULL),
('WR, EB (some), late'),
('WR, KKW, Roman'),
('EB, LB ---> Persian'),
('IB IA, MB --'),
('WR --> LB'),
('WR, KK, EB, Iron, Rom'),
('Byz'),
('MB'),
('WR, KKW, + [unintelligible] late MB'),
('EB, KKW, ---> Byz'),
('EB ----> IA'),
('EB, LB, ---> Persian'),
('EB, WR, Persian'),
('WR, KKW, Rom'),
('Mixed'),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
('WR, EB I'),
(NULL),
(NULL),
(NULL),
('WR, EB'),
('EB I'),
('EB I'),
('EB I'),
(NULL),
('EB I'),
('KK, Rom,EB'),
(NULL),
(NULL),
('EB I, II, III'),
('WR, EB'),
(NULL),
('EB I, EB II or III'),
('EB I, some late'),
('EB III'),
('EB I'),
('EB, Persian'),
('WR, EB, LB, Byz, KK'),
('EB to Roman'),
('EB I'),
('EB I'),
('EB I'),
('KK, Rom? Mixed'),
('EB I, EB III, KK, late'),
('WR, EB, LB'),
('KK, EB III'),
('WR, EB I'),
('EB'),
('EB, KK'),
(NULL),
('WR, EB I, KK (1)'),
(NULL),
('Rom? Byz?'),
(NULL),
(NULL),
('EB'),
('Wadi Rabah ---> Persian'),
('WR --> LB'),
('EB --------> Persian'),
('EB, Persian'),
('EB ---->  Persian'),
('WR, EB, LB, KK, Rom'),
(NULL),
('WR, EB, Rom'),
('WR, EB,Iron, Rom'),
('EB ---> Roman'),
('KK, WR, Persian'),
('WR ---> IA? LB?'),
('WR ---> late'),
('KK, WR, … Persian+'),
('WR … Persian'),
('EB, WR'),
('WR, EB'),
(NULL),
('EB III,EB I'),
(' ---> Persian'),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(''),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
('EB, Persian?'),
('WR - Rom'),
('EB, IA, Persian, Byz'),
('WR, LB, EB'),
('WR --> LB?'),
('WR ---> Persian'),
('WR, EB'),
(NULL),
(NULL),
('EB I'),
('EB II'),
('EB'),
('EB, IA?'),
('KKW'),
('EB'),
('WR, EB, Rom'),
('IA to Roman?'),
('KKW, EB … Roman, Persian'),
('EB'),
('EB'),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
('EB'),
(NULL),
('EB ---> Persian'),
('EB ---> late'),
('Rom, WR, Pers, EB'),
('WR to Roman'),
('Has everything!'),
('WR, EB'),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
('inlaid KKW sherd'),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
('Mixed WR - Byz'),
('Mixed WR - Byz'),
('Mixed'),
(NULL),
('EB to medieval'),
('Mixed'),
('WR to Persian'),
(NULL),
('EB to Medieval'),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
(NULL),
('EB, KK, Roman?');