INSERT INTO `materials` (`name`) VALUES
('Basalt - dense'),
('Basalt - vesicular'),
('Scoria'),
('Pumice'),
('Limestone'),
('Chalk'),
('Flint/Chert'),
('Sandstone'),
('Granite'),
('Unknown');

INSERT INTO `groundstone_types` (`name`) VALUES
('Indeterminate'),
('Vessel'),
('Mortar'),
('Cupmark'),
('Slab'),
('Pallette'),
('Anvil'),
('Grooved stone'),
('Handstone'),
('Pestle'),
('Grinder'),
('Pounder'),
('Scraper'),
('Multi-use'),
('Perforated'),
('Disc'),
('Drill'),
('Axe'),
('Hoe'),
('Worked stone'),
('Unknown');