INSERT INTO `tag_types` (`id`,`name`,`display_name`,`module_name`,`type_category`,`required`,`multiple`,`depends_on_id`,`order_column`) VALUES
(1,'Stone:Base-Type','Base Type','Stone','Tag',1,0,NULL,1),
(2,'Stone:Type-Passive','Type Passive','Stone','Tag',0,1,49,2),
(3,'Stone:Type-Active','Type Active','Stone','Tag',0,1,50,3),
(4,'Stone:Type-Non-Processor','Type Non-Processor','Stone','Tag',0,1,53,4),
(5,'Stone:Vessel-Rim','Rim','Stone','Tag',0,1,52,5),
(6,'Stone:Vessel-Wall','Wall','Stone','Tag',0,1,52,6),
(7,'Stone:Vessel-Base','Base','Stone','Tag',0,1,52,7),
(8,'Stone:Material','Material','Stone','Tag',1,0,NULL,8),
(9,'Stone:Preservation','Preservation','Stone','Tag',1,0,NULL,9),
(10,'Stone:Life-Stage','Life Stage','Stone','Tag',0,1,NULL,10),
(11,'Stone:Morphology','Morphology','Stone','Tag',0,1,NULL,11),
(12,'Stone:Profile','Profile','Stone','Tag',0,0,NULL,12),
(13,'Stone:Production','Production','Stone','Tag',0,1,NULL,13),
(14,'Stone:Use-Wear','Use Wear','Stone','Tag',0,1,NULL,14),

(201,'Glass:Base-Type','Base Type','Glass','Tag',1,1,NULL,201),
(202,'Glass:Vessel-Lamp','Vessel/Lamp','Glass','Tag',0,1,NULL,202),
(203,'Glass:Production','Production','Glass','Tag',0,1,NULL,203),
(204,'Glass:Color','Color','Glass','Tag',0,1,NULL,204),
(205,'Glass:Weathering','Weathering','Glass','Tag',0,1,NULL,205),
(206,'Glass:Weathering-Type','Weathering-Type','Glass','Tag',0,1,NULL,206),

(5001,'Periods:Base-Type','Periods','Tag','Tag',0,1,NULL,5001),
(5002,'Periods:Paleolithic','Paleolithic','Tag', 'Tag',0,1,5102,5002),
(5003,'Periods:Epipaleolithic','Epipaleolithic','Tag', 'Tag',0,1,5103,5003),
(5004,'Periods:Neolithic','Neolithic','Tag', 'Tag',0,1,5104,5004),
(5005,'Periods:Chalcolithic','Chalcolithic','Tag', 'Tag',0,1,5105,5005),
(5006,'Periods:Bronze','Bronze','Tag', 'Tag',0,1,5106,5006),
(5007,'Periods:Iron','Iron','Tag', 'Tag',0,1,5107,5007),
(5008,'Periods:Persian','Persian','Tag', 'Tag',0,1,5108,5008),
(5009,'Periods:Hellenistic','Hellenistic','Tag', 'Tag',0,1,5109,5009),
(5010,'Periods:Roman','Roman','Tag', 'Tag',0,1,5110,5010),
(5011,'Periods:Byzantine','Byzantine','Tag', 'Tag',0,1,5111,5011),
(5012,'Periods:Early-Islamic','Early-Islamic','Tag', 'Tag',0,1,5112,5012),
(5013,'Periods:Medieval','Medieval','Tag', 'Tag',0,1,5113,5013),
(5014,'Periods:Ottoman','Ottoman','Tag', 'Tag',0,1,5114,5014),
(5015,'Periods:Modern','Modern','Tag', 'Tag',0,1,5115,5015);

INSERT INTO `tags` (`id`, `name`, `slug`, `type`, `tag_type_id`, `order_column`, `created_at`, `updated_at`) VALUES 
(1,'{\"en\": \"Basalt-vesicular\"}','{\"en\": \"basalt-vesicular\"}','Stone:Material',8,1,NULL,NULL),
(2,'{\"en\": \"Basalt-dense\"}','{\"en\": \"basalt-dense\"}','Stone:Material',8,2,NULL,NULL),
(3,'{\"en\": \"Scoria\"}','{\"en\": \"scoria\"}','Stone:Material',8,3,NULL,NULL),
(4,'{\"en\": \"Pumice\"}','{\"en\": \"pumice\"}','Stone:Material',8,4,NULL,NULL),
(5,'{\"en\": \"Limestone\"}','{\"en\": \"limestone\"}','Stone:Material',8,5,NULL,NULL),
(6,'{\"en\": \"Chalk\"}','{\"en\": \"chalk\"}','Stone:Material',8,6,NULL,NULL),
(7,'{\"en\": \"Flint or Chert\"}','{\"en\": \"flint-or-chert\"}','Stone:Material',8,7,NULL,NULL),
(8,'{\"en\": \"Sandstone\"}','{\"en\": \"sandstone\"}','Stone:Material',8,8,NULL,NULL),
(9,'{\"en\": \"Granite\"}','{\"en\": \"granite\"}','Stone:Material',8,9,NULL,NULL),
(10,'{\"en\": \"Unknown\"}','{\"en\": \"unknown\"}','Stone:Material',8,100,NULL,NULL),
(11,'{\"en\": \"Incomplete\"}','{\"en\": \"incomplete\"}','Stone:Preservation',9,11,NULL,NULL),
(12,'{\"en\": \"Fragment\"}','{\"en\": \"fragment\"}','Stone:Preservation',9,12,NULL,NULL),
(13,'{\"en\": \"Complete\"}','{\"en\": \"complete\"}','Stone:Preservation',9,13,NULL,NULL),
(15,'{\"en\": \"Unused\"}','{\"en\": \"unused\"}','Stone:Life-Stage',10,15,NULL,NULL),
(16,'{\"en\": \"Blank\"}','{\"en\": \"blank\"}','Stone:Life-Stage',10,16,NULL,NULL),
(17,'{\"en\": \"Preform\"}','{\"en\": \"preform\"}','Stone:Life-Stage',10,17,NULL,NULL),
(18,'{\"en\": \"Debitage\"}','{\"en\": \"debitage\"}','Stone:Life-Stage',10,18,NULL,NULL),
(19,'{\"en\": \"Unfinished\"}','{\"en\": \"unfinished\"}','Stone:Life-Stage',10,19,NULL,NULL),
(20,'{\"en\": \"Intentional breakage\"}','{\"en\": \"intentional-breakage\"}','Stone:Life-Stage',10,20,NULL,NULL),
(21,'{\"en\": \"Fire-cracked\"}','{\"en\": \"fire-cracked\"}','Stone:Life-Stage',10,21,NULL,NULL),
(22,'{\"en\": \"Concave\"}','{\"en\": \"concave\"}','Stone:Profile',12,22,NULL,NULL),
(23,'{\"en\": \"Convex\"}','{\"en\": \"convex\"}','Stone:Profile',12,23,NULL,NULL),
(24,'{\"en\": \"Flat\"}','{\"en\": \"flat\"}','Stone:Profile',12,24,NULL,NULL),
(25,'{\"en\": \"Grinding\"}','{\"en\": \"grinding\"}','Stone:Production',13,25,NULL,NULL),
(26,'{\"en\": \"Pounding\"}','{\"en\": \"pounding\"}','Stone:Production',13,26,NULL,NULL),
(27,'{\"en\": \"Flaking\"}','{\"en\": \"flaking\"}','Stone:Production',13,27,NULL,NULL),
(28,'{\"en\": \"Abrading\"}','{\"en\": \"abrading\"}','Stone:Production',13,28,NULL,NULL),
(29,'{\"en\": \"Drilling\"}','{\"en\": \"drilling\"}','Stone:Production',13,29,NULL,NULL),
(30,'{\"en\": \"Cutting\"}','{\"en\": \"cutting\"}','Stone:Production',13,30,NULL,NULL),
(31,'{\"en\": \"Chiseling\"}','{\"en\": \"chiseling\"}','Stone:Production',13,31,NULL,NULL),
(32,'{\"en\": \"Polishing\"}','{\"en\": \"polishing\"}','Stone:Production',13,32,NULL,NULL),
(33,'{\"en\": \"Grinding\"}','{\"en\": \"grinding\"}','Stone:Use-Wear',14,33,NULL,NULL),
(34,'{\"en\": \"Pounding\"}','{\"en\": \"pounding\"}','Stone:Use-Wear',14,34,NULL,NULL),
(35,'{\"en\": \"Flaking\"}','{\"en\": \"flaking\"}','Stone:Use-Wear',14,35,NULL,NULL),
(36,'{\"en\": \"Abrading\"}','{\"en\": \"abrading\"}','Stone:Use-Wear',14,36,NULL,NULL),
(37,'{\"en\": \"Drilling\"}','{\"en\": \"drilling\"}','Stone:Use-Wear',14,37,NULL,NULL),
(38,'{\"en\": \"Residue\"}','{\"en\": \"residue\"}','Stone:Use-Wear',14,38,NULL,NULL),
(39,'{\"en\": \"Polish\"}','{\"en\": \"polish\"}','Stone:Use-Wear',14,39,NULL,NULL),
(40,'{\"en\": \"Use-light\"}','{\"en\": \"use-light\"}','Stone:Use-Wear',14,40,NULL,NULL),
(41,'{\"en\": \"Use-heavy\"}','{\"en\": \"use-heavy\"}','Stone:Use-Wear',14,41,NULL,NULL),
(42,'{\"en\": \"Face-single\"}','{\"en\": \"face-single\"}','Stone:Morphology',11,42,NULL,NULL),
(43,'{\"en\": \"Face-multiple\"}','{\"en\": \"face-multiple\"}','Stone:Morphology',11,43,NULL,NULL),
(44,'{\"en\": \"Depression\"}','{\"en\": \"depression\"}','Stone:Morphology',11,44,NULL,NULL),
(45,'{\"en\": \"Incision\"}','{\"en\": \"incision\"}','Stone:Morphology',11,45,NULL,NULL),
(46,'{\"en\": \"Groove or Notch\"}','{\"en\": \"groove-or-notch\"}','Stone:Morphology',11,46,NULL,NULL),
(47,'{\"en\": \"Sculpted\"}','{\"en\": \"sculpted\"}','Stone:Morphology',11,47,NULL,NULL),
(48,'{\"en\": \"Perforation\"}','{\"en\": \"perforation\"}','Stone:Morphology',11,48,NULL,NULL),
(49,'{\"en\": \"Passive\"}','{\"en\": \"passive\"}','Stone:Base-Type',1,49,NULL,NULL),
(50,'{\"en\": \"Active (handheld)\"}','{\"en\": \"active-handheld\"}','Stone:Base-Type',1,50,NULL,NULL),
(51,'{\"en\": \"Indeterminate Slab or Upper Grinding Stone\"}','{\"en\": \"indeterminate-slab-or-upper-grinding-stone\"}','Stone:Base-Type',1,51,NULL,NULL),
(52,'{\"en\": \"Vessel\"}','{\"en\": \"vessel\"}','Stone:Base-Type',1,52,NULL,NULL),
(53,'{\"en\": \"Non-Processor\"}','{\"en\": \"non-processor\"}','Stone:Base-Type',1,53,NULL,NULL),
(54,'{\"en\": \"Grinding Slab\"}','{\"en\": \"grinding-slab\"}','Stone:Type-Passive',2,54,NULL,NULL),
(55,'{\"en\": \"Mortar\"}','{\"en\": \"mortar\"}','Stone:Type-Passive',2,55,NULL,NULL),
(56,'{\"en\": \"Basin\"}','{\"en\": \"basin\"}','Stone:Type-Passive',2,56,NULL,NULL),
(57,'{\"en\": \"Anvil\"}','{\"en\": \"anvil\"}','Stone:Type-Passive',2,57,NULL,NULL),
(58,'{\"en\": \"Palette\"}','{\"en\": \"palette\"}','Stone:Type-Passive',2,58,NULL,NULL),
(59,'{\"en\": \"Grooved Stone\"}','{\"en\": \"grooved-stone\"}','Stone:Type-Passive',2,59,NULL,NULL),
(60,'{\"en\": \"Upper Grinding stone\"}','{\"en\": \"upper-grinding-stone\"}','Stone:Type-Active',3,60,NULL,NULL),
(61,'{\"en\": \"Pestle\"}','{\"en\": \"pestle\"}','Stone:Type-Active',3,61,NULL,NULL),
(62,'{\"en\": \"Grinder\"}','{\"en\": \"grinder\"}','Stone:Type-Active',3,62,NULL,NULL),
(63,'{\"en\": \"Pounder\"}','{\"en\": \"pounder\"}','Stone:Type-Active',3,63,NULL,NULL),
(64,'{\"en\": \"Abrader\"}','{\"en\": \"abrader\"}','Stone:Type-Active',3,64,NULL,NULL),
(65,'{\"en\": \"Scraper\"}','{\"en\": \"scraper\"}','Stone:Type-Active',3,65,NULL,NULL),
(67,'{\"en\": \"Multiple-Use\"}','{\"en\": \"multiple-use\"}','Stone:Type-Active',3,67,NULL,NULL),
(68,'{\"en\": \"Axe\"}','{\"en\": \"axe\"}','Stone:Type-Active',3,68,NULL,NULL),
(69,'{\"en\": \"Hoe\"}','{\"en\": \"hoe\"}','Stone:Type-Active',3,69,NULL,NULL),
(70,'{\"en\": \"Digging Stick Weight\"}','{\"en\": \"digging-stick-weight\"}','Stone:Type-Active',3,70,NULL,NULL),
(72,'{\"en\": \"Everted\"}','{\"en\": \"everted\"}','Stone:Vessel-Rim',5,72,NULL,NULL),
(73,'{\"en\": \"Straight\"}','{\"en\": \"straight\"}','Stone:Vessel-Rim',5,73,NULL,NULL),
(74,'{\"en\": \"Inverted\"}','{\"en\": \"inverted\"}','Stone:Vessel-Rim',5,74,NULL,NULL),
(75,'{\"en\": \"Convex\"}','{\"en\": \"convex\"}','Stone:Vessel-Wall',6,75,NULL,NULL),
(76,'{\"en\": \"Straight\"}','{\"en\": \"straight\"}','Stone:Vessel-Wall',6,76,NULL,NULL),
(77,'{\"en\": \"Splayed\"}','{\"en\": \"splayed\"}','Stone:Vessel-Wall',6,77,NULL,NULL),
(78,'{\"en\": \"Handle-vertical\"}','{\"en\": \"handle-vertical\"}','Stone:Vessel-Wall',6,78,NULL,NULL),
(79,'{\"en\": \"Handle-horizontal\"}','{\"en\": \"handle-horizontal\"}','Stone:Vessel-Wall',6,79,NULL,NULL),
(80,'{\"en\": \"Flat\"}','{\"en\": \"flat\"}','Stone:Vessel-Base',7,80,NULL,NULL),
(81,'{\"en\": \"Rounded\"}','{\"en\": \"rounded\"}','Stone:Vessel-Base',7,81,NULL,NULL),
(82,'{\"en\": \"Pedestal\"}','{\"en\": \"pedestal\"}','Stone:Vessel-Base',7,82,NULL,NULL),
(83,'{\"en\": \"Footed\"}','{\"en\": \"footed\"}','Stone:Vessel-Base',7,83,NULL,NULL),
(84,'{\"en\": \"Fenetsrated\"}','{\"en\": \"fenestrated\"}','Stone:Vessel-Base',7,84,NULL,NULL),
(85,'{\"en\": \"Ring\"}','{\"en\": \"ring\"}','Stone:Vessel-Base',7,85,NULL,NULL),
(86,'{\"en\": \"Disc\"}','{\"en\": \"disc\"}','Stone:Vessel-Base',7,86,NULL,NULL),
(87,'{\"en\": \"Architectural\"}','{\"en\": \"architectural\"}','Stone:Type-Non-Processor',4,87,NULL,NULL),
(88,'{\"en\": \"Socket\"}','{\"en\": \"socket\"}','Stone:Type-Non-Processor',4,88,NULL,NULL),
(89,'{\"en\": \"Stele\"}','{\"en\": \"stele\"}','Stone:Type-Non-Processor',4,89,NULL,NULL),
(91,'{\"en\": \"Perforated\"}','{\"en\": \"perforated\"}','Stone:Type-Non-Processor',4,91,NULL,NULL),
(92,'{\"en\": \"Tessera\"}','{\"en\": \"tessera\"}','Stone:Type-Non-Processor',4,92,NULL,NULL),
(93,'{\"en\": \"Bead\"}','{\"en\": \"bead\"}','Stone:Type-Non-Processor',4,93,NULL,NULL),
(94,'{\"en\": \"Figural Art\"}','{\"en\": \"figural-art\"}','Stone:Type-Non-Processor',4,94,NULL,NULL),
(95,'{\"en\": \"Worked Stone\"}','{\"en\": \"worked-stone\"}','Stone:Type-Non-Processor',4,95,NULL,NULL),
(96,'{\"en\": \"Manuport\"}','{\"en\": \"Manuport\"}','Stone:Type-Non-Processor',4,96,NULL,NULL),
(97,'{\"en\": \"Lid\"}','{\"en\": \"lid\"}','Stone:Type-Non-Processor',4,97,NULL,NULL),
(98,'{\"en\": \"Pebble or Burnisher\"}','{\"en\": \"pebble-or-burnisher\"}','Stone:Type-Non-Processor',4,98,NULL,NULL),
(100,'{\"en\": \"Slingstone\"}','{\"en\": \"slingstone\"}','Stone:Type-Active',3,100,NULL,NULL),
(101,'{\"en\": \"Exists\"}','{\"en\": \"exists\"}','Stone:Vessel-Rim',5,101,NULL,NULL),
(102,'{\"en\": \"Exists\"}','{\"en\": \"exists\"}','Stone:Vessel-Wall',6,102,NULL,NULL),
(103,'{\"en\": \"Exists\"}','{\"en\": \"exists\"}','Stone:Vessel-Base',7,103,NULL,NULL),
(104,'{\"en\": \"Scarab\"}','{\"en\": \"scarab\"}','Stone:Type-Non-Processor',4,98,NULL,NULL),
(105,'{\"en\": \"Amethyst\"}','{\"en\": \"amethyst\"}','Stone:Material',8,10,NULL,NULL),
(106,'{\"en\": \"Steatite\"}','{\"en\": \"steatite\"}','Stone:Material',8,11,NULL,NULL),

(5102,'{\"en\": \"Paleolithic\"}','{\"en\": \"Paleolithic\"}','Periods:Base-Type',5001,5002,NULL,NULL),
(5103,'{\"en\": \"Epipaleolithic\"}','{\"en\": \"Epipaleolithic\"}','Periods:Base-Type',5001, 5003,NULL,NULL),
(5104,'{\"en\": \"Neolithic\"}','{\"en\": \"Neolithic\"}','Periods:Base-Type',5001, 5004,NULL,NULL),
(5105,'{\"en\": \"Chalcolithic\"}','{\"en\": \"Chalcolithic\"}','Periods:Base-Type',5001, 5005,NULL,NULL),
(5106,'{\"en\": \"Bronze\"}','{\"en\": \"Bronze\"}','Periods:Base-Type',5001, 5006,NULL,NULL),
(5107,'{\"en\": \"Iron\"}','{\"en\": \"Iron\"}','Periods:Base-Type',5001, 5007,NULL,NULL),
(5108,'{\"en\": \"Persian\"}','{\"en\": \"Persian\"}','Periods:Base-Type',5001, 5008,NULL,NULL),
(5109,'{\"en\": \"Hellenistic\"}','{\"en\": \"Hellenistic\"}','Periods:Base-Type',5001, 5009,NULL,NULL),
(5110,'{\"en\": \"Roman\"}','{\"en\": \"Roman\"}','Periods:Base-Type',5001, 5010,NULL,NULL),
(5111,'{\"en\": \"Byzantine\"}','{\"en\": \"Byzantine\"}','Periods:Base-Type',5001, 5011,NULL,NULL),
(5112,'{\"en\": \"Early Islamic\"}','{\"en\": \"Early Islamic\"}','Periods:Base-Type',5001, 5012,NULL,NULL),
(5113,'{\"en\": \"Medieval\"}','{\"en\": \"Medieval\"}','Periods:Base-Type',5001, 5013,NULL,NULL),
(5114,'{\"en\": \"Ottoman\"}','{\"en\": \"Ottoman\"}','Periods:Base-Type',5001, 5014,NULL,NULL),
(5115,'{\"en\": \"Modern\"}','{\"en\": \"Modern\"}','Periods:Base-Type',5001, 5015,NULL,NULL),

(5401,'{\"en\": \"PPNA\"}','{\"en\": \"PPNA\"}','Periods:Neolithic',5004, 5401,NULL,NULL),
(5402,'{\"en\": \"PPNB\"}','{\"en\": \"PPNB\"}','Periods:Neolithic',5004, 5402,NULL,NULL),
(5403,'{\"en\": \"PPNC\"}','{\"en\": \"PPNC\"}','Periods:Neolithic',5004, 5403,NULL,NULL),
(5404,'{\"en\": \"Pottery Neolithic\"}','{\"en\": \"Pottery Neolithic\"}','Periods:Neolithic',5004, 5404,NULL,NULL),
(5405,'{\"en\": \"Yarmukian\"}','{\"en\": \"Yarmukian\"}','Periods:Neolithic',5004, 5405,NULL,NULL),
(5406,'{\"en\": \"Wadi Rabah\"}','{\"en\": \"Wadi Rabah\"}','Periods:Neolithic',5004, 5406,NULL,NULL),

(5601,'{\"en\": \"EB\"}','{\"en\": \"EB\"}','Periods:Bronze',5006, 5601,NULL,NULL),
(5602,'{\"en\": \"EB I\"}','{\"en\": \"EB I\"}','Periods:Bronze',5006, 5602,NULL,NULL),
(5603,'{\"en\": \"EB II\"}','{\"en\": \"EB II\"}','Periods:Bronze',5006, 5603,NULL,NULL),
(5604,'{\"en\": \"EB III\"}','{\"en\": \"EB III\"}','Periods:Bronze',5006, 5604,NULL,NULL),
(5605,'{\"en\": \"IB\"}','{\"en\": \"IB\"}','Periods:Bronze',5006, 5605,NULL,NULL),
(5606,'{\"en\": \"MB\"}','{\"en\": \"MB\"}','Periods:Bronze',5006, 5606,NULL,NULL),
(5608,'{\"en\": \"MB IIA\"}','{\"en\": \"MB IIA\"}','Periods:Bronze',5006, 5608,NULL,NULL),
(5609,'{\"en\": \"MB IIB\"}','{\"en\": \"MB IIB\"}','Periods:Bronze',5006, 5609,NULL,NULL),
(5610,'{\"en\": \"MB IIC\"}','{\"en\": \"MB IIC\"}','Periods:Bronze',5006, 5610,NULL,NULL),
(5611,'{\"en\": \"LB\"}','{\"en\": \"LB\"}','Periods:Bronze',5006, 5611,NULL,NULL),
(5612,'{\"en\": \"LB I\"}','{\"en\": \"LB I\"}','Periods:Bronze',5006, 5612,NULL,NULL),
(5613,'{\"en\": \"LB IIA\"}','{\"en\": \"LB IIA\"}','Periods:Bronze',5006, 5613,NULL,NULL),
(5614,'{\"en\": \"LB IIB\"}','{\"en\": \"LB IIB\"}','Periods:Bronze',5006, 5614,NULL,NULL),

(5701,'{\"en\": \"Ir\"}','{\"en\": \"Ir\"}','Periods:Iron',5007, 5701,NULL,NULL),
(5702,'{\"en\": \"Ir IA\"}','{\"en\": \"Ir IA\"}','Periods:Iron',5007, 5702,NULL,NULL),
(5703,'{\"en\": \"Ir IB\"}','{\"en\": \"Ir IB\"}','Periods:Iron',5007, 5703,NULL,NULL),
(5704,'{\"en\": \"Ir IIA\"}','{\"en\": \"Ir IIA\"}','Periods:Iron',5007, 5704,NULL,NULL),
(5705,'{\"en\": \"Ir IIB\"}','{\"en\": \"Ir IIB\"}','Periods:Iron',5007, 5705,NULL,NULL),
(5706,'{\"en\": \"Ir IIC\"}','{\"en\": \"Ir IIC\"}','Periods:Iron',5007, 5706,NULL,NULL),

(5901,'{\"en\": \"Early Hellenistic\"}','{\"en\": \"Hellenistic\"}','Periods:Hellenistic',5009, 1,NULL,NULL),
(5902,'{\"en\": \"Late Hellenistic\"}','{\"en\": \"Late Hellenistic\"}','Periods:Hellenistic',5009, 2,NULL,NULL),

(6001,'{\"en\": \"Early Roman\"}','{\"en\": \"Early Roman\"}','Periods:Roman',5010, 1,NULL,NULL),
(6002,'{\"en\": \"Herodian\"}','{\"en\": \"Herodian\"}','Periods:Roman',5010, 2,NULL,NULL),
(6003,'{\"en\": \"Middle Roman\"}','{\"en\": \"Middle Roman\"}','Periods:Roman',5010, 3,NULL,NULL),
(6004,'{\"en\": \"Late Roman\"}','{\"en\": \"Late Roman\"}','Periods:Roman',5010, 4,NULL,NULL),

(6201,'{\"en\": \"Umayyad\"}','{\"en\": \"Umayyad\"}','Periods:Early-Islamic',5012, 1,NULL,NULL),
(6202,'{\"en\": \"Abbasid\"}','{\"en\": \"Abbasid\"}','Periods:Early-Islamic',5012, 2,NULL,NULL),
(6203,'{\"en\": \"Fatimid\"}','{\"en\": \"Fatimid\"}','Periods:Early-Islamic',5012, 3,NULL,NULL),


(6303,'{\"en\": \"Crusader\"}','{\"en\": \"Crusader\"}','Periods:Medieval',5013, 3,NULL,NULL),
(6304,'{\"en\": \"Ayyubid\"}','{\"en\": \"Ayyubid\"}','Periods:Medieval',5013, 4,NULL,NULL),
(6305,'{\"en\": \"Mamluk\"}','{\"en\": \"Mamluk\"}','Periods:Medieval',5013, 5,NULL,NULL),

(6501,'{\"en\": \"1917-1948\"}','{\"en\": \"1917-1948\"}','Periods:Modern',5015, 1,NULL,NULL),
(6502,'{\"en\": \"1949-present\"}','{\"en\": \"1949-present\"}','Periods:Modern',5015, 2,NULL,NULL);








