INSERT INTO `tag_types` (`id`, `category`, `name`, `required`, `multiple`, `depends_on`, `order_column`) VALUES 
(1,'Stone','Stone:Base-Type',1,0,NULL,1),
(2,'Stone','Stone:Type-Passive',0,1,NULL,2),
(3,'Stone','Stone:Type-Active',0,1,NULL,3),
(4,'Stone','Stone:Type-Non-Processor',0,1,NULL,4),
(5,'Stone','Stone:Vessel-Rim',0,1,NULL,5),
(6,'Stone','Stone:Vessel-Wall',0,1,NULL,6),
(7,'Stone','Stone:Vessel-Base',0,1,NULL,7),
(8,'Stone','Stone:Material',1,0,NULL,8),
(9,'Stone','Stone:Preservation',1,0,NULL,9),
(10,'Stone','Stone:Life-Stage',0,1,NULL,10),
(11,'Stone','Stone:Morphology',0,1,NULL,11),
(12,'Stone','Stone:Profile',0,0,NULL,12),
(13,'Stone','Stone:Production',0,1,NULL,13),
(14,'Stone','Stone:Use-Wear',0,1,NULL,14);

INSERT INTO `tags` (`id`,`name`,`slug`,`type`,`tag_type_id`,`order_column`,`created_at`,`updated_at`) VALUES 
(1,'{\"en\": \"Basalt-vesicular\"}','{\"en\": \"basalt-vesicular\"}','Stone:Material',8,1,NULL,NULL),(2,'{\"en\": \"Basalt-dense\"}','{\"en\": \"basalt-dense\"}','Stone:Material',8,2,NULL,NULL),(3,'{\"en\": \"Scoria\"}','{\"en\": \"scoria\"}','Stone:Material',8,3,NULL,NULL),(4,'{\"en\": \"Pumice\"}','{\"en\": \"pumice\"}','Stone:Material',8,4,NULL,NULL),(5,'{\"en\": \"Limestone\"}','{\"en\": \"limestone\"}','Stone:Material',8,5,NULL,NULL),(6,'{\"en\": \"Chalk\"}','{\"en\": \"chalk\"}','Stone:Material',8,6,NULL,NULL),(7,'{\"en\": \"Flint or Chert\"}','{\"en\": \"flint-or-chert\"}','Stone:Material',8,7,NULL,NULL),(8,'{\"en\": \"Sandstone\"}','{\"en\": \"sandstone\"}','Stone:Material',8,8,NULL,NULL),(9,'{\"en\": \"Granite\"}','{\"en\": \"granite\"}','Stone:Material',8,9,NULL,NULL),(10,'{\"en\": \"Unknown\"}','{\"en\": \"unknown\"}','Stone:Material',8,10,NULL,NULL),(11,'{\"en\": \"Incomplete\"}','{\"en\": \"incomplete\"}','Stone:Preservation',9,11,NULL,NULL),(12,'{\"en\": \"Fragment\"}','{\"en\": \"fragment\"}','Stone:Preservation',9,12,NULL,NULL),(13,'{\"en\": \"Complete\"}','{\"en\": \"complete\"}','Stone:Preservation',9,13,NULL,NULL),(15,'{\"en\": \"Unused\"}','{\"en\": \"unused\"}','Stone:Life-Stage',10,15,NULL,NULL),(16,'{\"en\": \"Blank\"}','{\"en\": \"blank\"}','Stone:Life-Stage',10,16,NULL,NULL),(17,'{\"en\": \"Preform\"}','{\"en\": \"preform\"}','Stone:Life-Stage',10,17,NULL,NULL),(18,'{\"en\": \"Debitage\"}','{\"en\": \"debitage\"}','Stone:Life-Stage',10,18,NULL,NULL),(19,'{\"en\": \"Unfinished\"}','{\"en\": \"unfinished\"}','Stone:Life-Stage',10,19,NULL,NULL),(20,'{\"en\": \"Intentional breakage\"}','{\"en\": \"intentional-breakage\"}','Stone:Life-Stage',10,20,NULL,NULL),(21,'{\"en\": \"Fire-cracked\"}','{\"en\": \"fire-cracked\"}','Stone:Life-Stage',10,21,NULL,NULL),(22,'{\"en\": \"Concave\"}','{\"en\": \"concave\"}','Stone:Profile',12,22,NULL,NULL),(23,'{\"en\": \"Convex\"}','{\"en\": \"convex\"}','Stone:Profile',12,23,NULL,NULL),(24,'{\"en\": \"Flat\"}','{\"en\": \"flat\"}','Stone:Profile',12,24,NULL,NULL),(25,'{\"en\": \"Grinding\"}','{\"en\": \"grinding\"}','Stone:Production',13,25,NULL,NULL),(26,'{\"en\": \"Pounding\"}','{\"en\": \"pounding\"}','Stone:Production',13,26,NULL,NULL),(27,'{\"en\": \"Flaking\"}','{\"en\": \"flaking\"}','Stone:Production',13,27,NULL,NULL),(28,'{\"en\": \"Abrading\"}','{\"en\": \"abrading\"}','Stone:Production',13,28,NULL,NULL),(29,'{\"en\": \"Drilling\"}','{\"en\": \"drilling\"}','Stone:Production',13,29,NULL,NULL),(30,'{\"en\": \"Cutting\"}','{\"en\": \"cutting\"}','Stone:Production',13,30,NULL,NULL),(31,'{\"en\": \"Chiseling\"}','{\"en\": \"chiseling\"}','Stone:Production',13,31,NULL,NULL),(32,'{\"en\": \"Polishing\"}','{\"en\": \"polishing\"}','Stone:Production',13,32,NULL,NULL),(33,'{\"en\": \"Grinding\"}','{\"en\": \"grinding\"}','Stone:Use-Wear',14,33,NULL,NULL),(34,'{\"en\": \"Pounding\"}','{\"en\": \"pounding\"}','Stone:Use-Wear',14,34,NULL,NULL),(35,'{\"en\": \"Flaking\"}','{\"en\": \"flaking\"}','Stone:Use-Wear',14,35,NULL,NULL),(36,'{\"en\": \"Abrading\"}','{\"en\": \"abrading\"}','Stone:Use-Wear',14,36,NULL,NULL),(37,'{\"en\": \"Drilling\"}','{\"en\": \"drilling\"}','Stone:Use-Wear',14,37,NULL,NULL),(38,'{\"en\": \"Residue\"}','{\"en\": \"residue\"}','Stone:Use-Wear',14,38,NULL,NULL),(39,'{\"en\": \"Polish\"}','{\"en\": \"polish\"}','Stone:Use-Wear',14,39,NULL,NULL),(40,'{\"en\": \"Use-light\"}','{\"en\": \"use-light\"}','Stone:Use-Wear',14,40,NULL,NULL),(41,'{\"en\": \"Use-heavy\"}','{\"en\": \"use-heavy\"}','Stone:Use-Wear',14,41,NULL,NULL),(42,'{\"en\": \"Face-single\"}','{\"en\": \"face-single\"}','Stone:Morphology',11,42,NULL,NULL),(43,'{\"en\": \"Face-multiple\"}','{\"en\": \"face-multiple\"}','Stone:Morphology',11,43,NULL,NULL),(44,'{\"en\": \"Depression\"}','{\"en\": \"depression\"}','Stone:Morphology',11,44,NULL,NULL),(45,'{\"en\": \"Incision\"}','{\"en\": \"incision\"}','Stone:Morphology',11,45,NULL,NULL),(46,'{\"en\": \"Groove or Notch\"}','{\"en\": \"groove-or-notch\"}','Stone:Morphology',11,46,NULL,NULL),(47,'{\"en\": \"Sculpted\"}','{\"en\": \"sculpted\"}','Stone:Morphology',11,47,NULL,NULL),(48,'{\"en\": \"Perforation\"}','{\"en\": \"perforation\"}','Stone:Morphology',11,48,NULL,NULL),(49,'{\"en\": \"Passive\"}','{\"en\": \"passive\"}','Stone:Base-Type',1,49,NULL,NULL),(50,'{\"en\": \"Active (handheld)\"}','{\"en\": \"active-handheld\"}','Stone:Base-Type',1,50,NULL,NULL),(51,'{\"en\": \"Active or Passive\"}','{\"en\": \"active-or-passive\"}','Stone:Base-Type',1,51,NULL,NULL),(52,'{\"en\": \"Vessel\"}','{\"en\": \"vessel\"}','Stone:Base-Type',1,52,NULL,NULL),(53,'{\"en\": \"Non-Processor\"}','{\"en\": \"non-processor\"}','Stone:Base-Type',1,53,NULL,NULL),(54,'{\"en\": \"Grinding Slab\"}','{\"en\": \"grinding-slab\"}','Stone:Type-Passive',2,54,NULL,NULL),(55,'{\"en\": \"Mortar\"}','{\"en\": \"mortar\"}','Stone:Type-Passive',2,55,NULL,NULL),(56,'{\"en\": \"Basin\"}','{\"en\": \"basin\"}','Stone:Type-Passive',2,56,NULL,NULL),(57,'{\"en\": \"Anvil\"}','{\"en\": \"anvil\"}','Stone:Type-Passive',2,57,NULL,NULL),(58,'{\"en\": \"Palette\"}','{\"en\": \"palette\"}','Stone:Type-Passive',2,58,NULL,NULL),(59,'{\"en\": \"Grooved Stone\"}','{\"en\": \"grooved-stone\"}','Stone:Type-Passive',2,59,NULL,NULL),(60,'{\"en\": \"Upper Grinding stone\"}','{\"en\": \"upper-grinding-stone\"}','Stone:Type-Active',3,60,NULL,NULL),(61,'{\"en\": \"Pestle\"}','{\"en\": \"pestle\"}','Stone:Type-Active',3,61,NULL,NULL),(62,'{\"en\": \"Grinder\"}','{\"en\": \"grinder\"}','Stone:Type-Active',3,62,NULL,NULL),(63,'{\"en\": \"Pounder\"}','{\"en\": \"pounder\"}','Stone:Type-Active',3,63,NULL,NULL),(64,'{\"en\": \"Abrader\"}','{\"en\": \"abrader\"}','Stone:Type-Active',3,64,NULL,NULL),(65,'{\"en\": \"Scraper\"}','{\"en\": \"scraper\"}','Stone:Type-Active',3,65,NULL,NULL),(67,'{\"en\": \"Multiple-Use\"}','{\"en\": \"multiple-use\"}','Stone:Type-Active',3,67,NULL,NULL),(68,'{\"en\": \"Axe\"}','{\"en\": \"axe\"}','Stone:Type-Active',3,68,NULL,NULL),(69,'{\"en\": \"Hoe\"}','{\"en\": \"hoe\"}','Stone:Type-Active',3,69,NULL,NULL),
(70,'{\"en\": \"Digging Stick Weight\"}','{\"en\": \"digging-stick-weight\"}','Stone:Type-Active',3,70,NULL,NULL),
(71,'{\"en\": \"Indeterminate\"}','{\"en\": \"indeterminate\"}','Stone:Type-Active-Or-Passive',1,71,NULL,NULL),
(72,'{\"en\": \"Everted\"}','{\"en\": \"everted\"}','Stone:Vessel-Rim',5,72,NULL,NULL),(73,'{\"en\": \"Straight\"}','{\"en\": \"straight\"}','Stone:Vessel-Rim',5,73,NULL,NULL),(74,'{\"en\": \"Inverted\"}','{\"en\": \"inverted\"}','Stone:Vessel-Rim',5,74,NULL,NULL),(75,'{\"en\": \"Convex\"}','{\"en\": \"convex\"}','Stone:Vessel-Wall',6,75,NULL,NULL),(76,'{\"en\": \"Straight\"}','{\"en\": \"straight\"}','Stone:Vessel-Wall',6,76,NULL,NULL),(77,'{\"en\": \"Splayed\"}','{\"en\": \"splayed\"}','Stone:Vessel-Wall',6,77,NULL,NULL),(78,'{\"en\": \"Handle-vertical\"}','{\"en\": \"handle-vertical\"}','Stone:Vessel-Wall',6,78,NULL,NULL),(79,'{\"en\": \"Handle-horizontal\"}','{\"en\": \"handle-horizontal\"}','Stone:Vessel-Wall',6,79,NULL,NULL),(80,'{\"en\": \"Flat\"}','{\"en\": \"flat\"}','Stone:Vessel-Base',7,80,NULL,NULL),(81,'{\"en\": \"Rounded\"}','{\"en\": \"rounded\"}','Stone:Vessel-Base',7,81,NULL,NULL),(82,'{\"en\": \"Pedestal\"}','{\"en\": \"pedestal\"}','Stone:Vessel-Base',7,82,NULL,NULL),(83,'{\"en\": \"Footed\"}','{\"en\": \"footed\"}','Stone:Vessel-Base',7,83,NULL,NULL),(84,'{\"en\": \"Fenetsrated\"}','{\"en\": \"fenestrated\"}','Stone:Vessel-Base',7,84,NULL,NULL),(85,'{\"en\": \"Ring\"}','{\"en\": \"ring\"}','Stone:Vessel-Base',7,85,NULL,NULL),(86,'{\"en\": \"Disc\"}','{\"en\": \"disc\"}','Stone:Vessel-Base',7,86,NULL,NULL),(87,'{\"en\": \"Architectural\"}','{\"en\": \"architectural\"}','Stone:Type-Non-Processor',4,87,NULL,NULL),(88,'{\"en\": \"Socket\"}','{\"en\": \"socket\"}','Stone:Type-Non-Processor',4,88,NULL,NULL),(89,'{\"en\": \"Stele\"}','{\"en\": \"stele\"}','Stone:Type-Non-Processor',4,89,NULL,NULL),(91,'{\"en\": \"Perforated\"}','{\"en\": \"perforated\"}','Stone:Type-Non-Processor',4,91,NULL,NULL),(92,'{\"en\": \"Tessera\"}','{\"en\": \"tessera\"}','Stone:Type-Non-Processor',4,92,NULL,NULL),(93,'{\"en\": \"Bead\"}','{\"en\": \"bead\"}','Stone:Type-Non-Processor',4,93,NULL,NULL),(94,'{\"en\": \"Figural Art\"}','{\"en\": \"figural-art\"}','Stone:Type-Non-Processor',4,94,NULL,NULL),(95,'{\"en\": \"Worked Stone\"}','{\"en\": \"worked-stone\"}','Stone:Type-Non-Processor',4,95,NULL,NULL),(96,'{\"en\": \"Manuport\"}','{\"en\": \"Manuport\"}','Stone:Type-Non-Processor',4,96,NULL,NULL),(97,'{\"en\": \"Lid\"}','{\"en\": \"lid\"}','Stone:Type-Non-Processor',4,97,NULL,NULL),(98,'{\"en\": \"Pebble or Burnisher\"}','{\"en\": \"pebble-or-burnisher\"}','Stone:Type-Non-Processor',4,98,NULL,NULL),(100,'{\"en\": \"Slingstone\"}','{\"en\": \"slingstone\"}','Stone:Type-Active',3,100,NULL,NULL),(101,'{\"en\": \"Exists\"}','{\"en\": \"exists\"}','Stone:Vessel-Rim',5,101,NULL,NULL),(102,'{\"en\": \"Exists\"}','{\"en\": \"exists\"}','Stone:Vessel-Wall',6,102,NULL,NULL),(103,'{\"en\": \"Exists\"}','{\"en\": \"exists\"}','Stone:Vessel-Base',7,103,NULL,NULL);

/*




INSERT INTO `tags` (`id`, `name`, `slug`, `type`, `order_column`, `created_at`, `updated_at`) VALUES 
(1,'{\"en\": \"Basalt-vesicular\"}','{\"en\": \"basalt-vesicular\"}','Stone:Material',1,NULL,NULL),
(2,'{\"en\": \"Basalt-dense\"}','{\"en\": \"basalt-dense\"}','Stone:Material',2,NULL,NULL),
(3,'{\"en\": \"Scoria\"}','{\"en\": \"scoria\"}','Stone:Material',3,NULL,NULL),
(4,'{\"en\": \"Pumice\"}','{\"en\": \"pumice\"}','Stone:Material',4,NULL,NULL),
(5,'{\"en\": \"Limestone\"}','{\"en\": \"limestone\"}','Stone:Material',5,NULL,NULL),
(6,'{\"en\": \"Chalk\"}','{\"en\": \"chalk\"}','Stone:Material',6,NULL,NULL),
(7,'{\"en\": \"Flint or Chert\"}','{\"en\": \"flint-or-chert\"}','Stone:Material',7,NULL,NULL),
(8,'{\"en\": \"Sandstone\"}','{\"en\": \"sandstone\"}','Stone:Material',8,NULL,NULL),
(9,'{\"en\": \"Granite\"}','{\"en\": \"granite\"}','Stone:Material',9,NULL,NULL),
(10,'{\"en\": \"Unknown\"}','{\"en\": \"unknown\"}','Stone:Material',10,NULL,NULL),
(11,'{\"en\": \"Incomplete\"}','{\"en\": \"incomplete\"}','Stone:Preservation',11,NULL,NULL),
(12,'{\"en\": \"Fragment\"}','{\"en\": \"fragment\"}','Stone:Preservation',12,NULL,NULL),
(13,'{\"en\": \"Complete\"}','{\"en\": \"complete\"}','Stone:Preservation',13,NULL,NULL),
(15,'{\"en\": \"Unused\"}','{\"en\": \"unused\"}','Stone:Life-Stage',15,NULL,NULL),
(16,'{\"en\": \"Blank\"}','{\"en\": \"blank\"}','Stone:Life-Stage',16,NULL,NULL),
(17,'{\"en\": \"Preform\"}','{\"en\": \"preform\"}','Stone:Life-Stage',17,NULL,NULL),
(18,'{\"en\": \"Debitage\"}','{\"en\": \"debitage\"}','Stone:Life-Stage',18,NULL,NULL),
(19,'{\"en\": \"Unfinished\"}','{\"en\": \"unfinished\"}','Stone:Life-Stage',19,NULL,NULL),
(20,'{\"en\": \"Intentional breakage\"}','{\"en\": \"intentional-breakage\"}','Stone:Life-Stage',20,NULL,NULL),
(21,'{\"en\": \"Fire-cracked\"}','{\"en\": \"fire-cracked\"}','Stone:Life-Stage',21,NULL,NULL),
(22,'{\"en\": \"Concave\"}','{\"en\": \"concave\"}','Stone:Profile',22,NULL,NULL),
(23,'{\"en\": \"Convex\"}','{\"en\": \"convex\"}','Stone:Profile',23,NULL,NULL),
(24,'{\"en\": \"Flat\"}','{\"en\": \"flat\"}','Stone:Profile',24,NULL,NULL),
(25,'{\"en\": \"Grinding\"}','{\"en\": \"grinding\"}','Stone:Production',25,NULL,NULL),
(26,'{\"en\": \"Pounding\"}','{\"en\": \"pounding\"}','Stone:Production',26,NULL,NULL),
(27,'{\"en\": \"Flaking\"}','{\"en\": \"flaking\"}','Stone:Production',27,NULL,NULL),
(28,'{\"en\": \"Abrading\"}','{\"en\": \"abrading\"}','Stone:Production',28,NULL,NULL),
(29,'{\"en\": \"Drilling\"}','{\"en\": \"drilling\"}','Stone:Production',29,NULL,NULL),
(30,'{\"en\": \"Cutting\"}','{\"en\": \"cutting\"}','Stone:Production',30,NULL,NULL),
(31,'{\"en\": \"Chiseling\"}','{\"en\": \"chiseling\"}','Stone:Production',31,NULL,NULL),
(32,'{\"en\": \"Polishing\"}','{\"en\": \"polishing\"}','Stone:Production',32,NULL,NULL),
(33,'{\"en\": \"Grinding\"}','{\"en\": \"grinding\"}','Stone:Use-Wear',33,NULL,NULL),
(34,'{\"en\": \"Pounding\"}','{\"en\": \"pounding\"}','Stone:Use-Wear',34,NULL,NULL),
(35,'{\"en\": \"Flaking\"}','{\"en\": \"flaking\"}','Stone:Use-Wear',35,NULL,NULL),
(36,'{\"en\": \"Abrading\"}','{\"en\": \"abrading\"}','Stone:Use-Wear',36,NULL,NULL),
(37,'{\"en\": \"Drilling\"}','{\"en\": \"drilling\"}','Stone:Use-Wear',37,NULL,NULL),
(38,'{\"en\": \"Residue\"}','{\"en\": \"residue\"}','Stone:Use-Wear',38,NULL,NULL),
(39,'{\"en\": \"Polish\"}','{\"en\": \"polish\"}','Stone:Use-Wear',39,NULL,NULL),
(40,'{\"en\": \"Use-light\"}','{\"en\": \"use-light\"}','Stone:Use-Wear',40,NULL,NULL),
(41,'{\"en\": \"Use-heavy\"}','{\"en\": \"use-heavy\"}','Stone:Use-Wear',41,NULL,NULL),
(42,'{\"en\": \"Face-single\"}','{\"en\": \"face-single\"}','Stone:Morphology',42,NULL,NULL),
(43,'{\"en\": \"Face-multiple\"}','{\"en\": \"face-multiple\"}','Stone:Morphology',43,NULL,NULL),
(44,'{\"en\": \"Depression\"}','{\"en\": \"depression\"}','Stone:Morphology',44,NULL,NULL),
(45,'{\"en\": \"Incision\"}','{\"en\": \"incision\"}','Stone:Morphology',45,NULL,NULL),
(46,'{\"en\": \"Groove or Notch\"}','{\"en\": \"groove-or-notch\"}','Stone:Morphology',46,NULL,NULL),
(47,'{\"en\": \"Sculpted\"}','{\"en\": \"sculpted\"}','Stone:Morphology',47,NULL,NULL),
(48,'{\"en\": \"Perforation\"}','{\"en\": \"perforation\"}','Stone:Morphology',48,NULL,NULL),
(49,'{\"en\": \"Passive\"}','{\"en\": \"passive\"}','Stone:Base-Type',49,NULL,NULL),
(50,'{\"en\": \"Active (handheld)\"}','{\"en\": \"active-handheld\"}','Stone:Base-Type',50,NULL,NULL),
(51,'{\"en\": \"Active or Passive\"}','{\"en\": \"active-or-passive\"}','Stone:Base-Type',51,NULL,NULL),
(52,'{\"en\": \"Vessel\"}','{\"en\": \"vessel\"}','Stone:Base-Type',52,NULL,NULL),
(53,'{\"en\": \"Non-Processor\"}','{\"en\": \"non-processor\"}','Stone:Base-Type',53,NULL,NULL),
(54,'{\"en\": \"Grinding Slab\"}','{\"en\": \"grinding-slab\"}','Stone:Type-Passive',54,NULL,NULL),
(55,'{\"en\": \"Mortar\"}','{\"en\": \"mortar\"}','Stone:Type-Passive',55,NULL,NULL),
(56,'{\"en\": \"Basin\"}','{\"en\": \"basin\"}','Stone:Type-Passive',56,NULL,NULL),
(57,'{\"en\": \"Anvil\"}','{\"en\": \"anvil\"}','Stone:Type-Passive',57,NULL,NULL),
(58,'{\"en\": \"Palette\"}','{\"en\": \"palette\"}','Stone:Type-Passive',58,NULL,NULL),
(59,'{\"en\": \"Grooved Stone\"}','{\"en\": \"grooved-stone\"}','Stone:Type-Passive',59,NULL,NULL),
(60,'{\"en\": \"Upper Grinding stone\"}','{\"en\": \"upper-grinding-stone\"}','Stone:Type-Active',60,NULL,NULL),
(61,'{\"en\": \"Pestle\"}','{\"en\": \"pestle\"}','Stone:Type-Active',61,NULL,NULL),
(62,'{\"en\": \"Grinder\"}','{\"en\": \"grinder\"}','Stone:Type-Active',62,NULL,NULL),
(63,'{\"en\": \"Pounder\"}','{\"en\": \"pounder\"}','Stone:Type-Active',63,NULL,NULL),
(64,'{\"en\": \"Abrader\"}','{\"en\": \"abrader\"}','Stone:Type-Active',64,NULL,NULL),
(65,'{\"en\": \"Scraper\"}','{\"en\": \"scraper\"}','Stone:Type-Active',65,NULL,NULL),
(67,'{\"en\": \"Multiple-Use\"}','{\"en\": \"multiple-use\"}','Stone:Type-Active',67,NULL,NULL),
(68,'{\"en\": \"Axe\"}','{\"en\": \"axe\"}','Stone:Type-Active',68,NULL,NULL),
(69,'{\"en\": \"Hoe\"}','{\"en\": \"hoe\"}','Stone:Type-Active',69,NULL,NULL),
(70,'{\"en\": \"Digging Stick Weight\"}','{\"en\": \"digging-stick-weight\"}','Stone:Type-Active',70,NULL,NULL),
(71,'{\"en\": \"Indeterminate\"}','{\"en\": \"indeterminate\"}','Stone:Type-Active-Or-Passive',71,NULL,NULL),
(72,'{\"en\": \"Everted\"}','{\"en\": \"everted\"}','Stone:Vessel-Rim',72,NULL,NULL),
(73,'{\"en\": \"Straight\"}','{\"en\": \"straight\"}','Stone:Vessel-Rim',73,NULL,NULL),
(74,'{\"en\": \"Inverted\"}','{\"en\": \"inverted\"}','Stone:Vessel-Rim',74,NULL,NULL),
(75,'{\"en\": \"Convex\"}','{\"en\": \"convex\"}','Stone:Vessel-Wall',75,NULL,NULL),
(76,'{\"en\": \"Straight\"}','{\"en\": \"straight\"}','Stone:Vessel-Wall',76,NULL,NULL),
(77,'{\"en\": \"Splayed\"}','{\"en\": \"splayed\"}','Stone:Vessel-Wall',77,NULL,NULL),
(78,'{\"en\": \"Handle-vertical\"}','{\"en\": \"handle-vertical\"}','Stone:Vessel-Wall',78,NULL,NULL),
(79,'{\"en\": \"Handle-horizontal\"}','{\"en\": \"handle-horizontal\"}','Stone:Vessel-Wall',79,NULL,NULL),
(80,'{\"en\": \"Flat\"}','{\"en\": \"flat\"}','Stone:Vessel-Base',80,NULL,NULL),
(81,'{\"en\": \"Rounded\"}','{\"en\": \"rounded\"}','Stone:Vessel-Base',81,NULL,NULL),
(82,'{\"en\": \"Pedestal\"}','{\"en\": \"pedestal\"}','Stone:Vessel-Base',82,NULL,NULL),
(83,'{\"en\": \"Footed\"}','{\"en\": \"footed\"}','Stone:Vessel-Base',83,NULL,NULL),
(84,'{\"en\": \"Fenetsrated\"}','{\"en\": \"fenestrated\"}','Stone:Vessel-Base',84,NULL,NULL),
(85,'{\"en\": \"Ring\"}','{\"en\": \"ring\"}','Stone:Vessel-Base',85,NULL,NULL),
(86,'{\"en\": \"Disc\"}','{\"en\": \"disc\"}','Stone:Vessel-Base',86,NULL,NULL),
(87,'{\"en\": \"Architectural\"}','{\"en\": \"architectural\"}','Stone:Type-Non-Processor',87,NULL,NULL),
(88,'{\"en\": \"Socket\"}','{\"en\": \"socket\"}','Stone:Type-Non-Processor',88,NULL,NULL),
(89,'{\"en\": \"Stele\"}','{\"en\": \"stele\"}','Stone:Type-Non-Processor',89,NULL,NULL),
(91,'{\"en\": \"Perforated\"}','{\"en\": \"perforated\"}','Stone:Type-Non-Processor',91,NULL,NULL),
(92,'{\"en\": \"Tessera\"}','{\"en\": \"tessera\"}','Stone:Type-Non-Processor',92,NULL,NULL),
(93,'{\"en\": \"Bead\"}','{\"en\": \"bead\"}','Stone:Type-Non-Processor',93,NULL,NULL),
(94,'{\"en\": \"Figural Art\"}','{\"en\": \"figural-art\"}','Stone:Type-Non-Processor',94,NULL,NULL),
(95,'{\"en\": \"Worked Stone\"}','{\"en\": \"worked-stone\"}','Stone:Type-Non-Processor',95,NULL,NULL),
(96,'{\"en\": \"Manuport\"}','{\"en\": \"Manuport\"}','Stone:Type-Non-Processor',96,NULL,NULL),
(97,'{\"en\": \"Lid\"}','{\"en\": \"lid\"}','Stone:Type-Non-Processor',97,NULL,NULL),
(98,'{\"en\": \"Pebble or Burnisher\"}','{\"en\": \"pebble-or-burnisher\"}','Stone:Type-Non-Processor',98,NULL,NULL),
(100,'{\"en\": \"Slingstone\"}','{\"en\": \"slingstone\"}','Stone:Type-Active',100,NULL,NULL),
(101,'{\"en\": \"Exists\"}','{\"en\": \"exists\"}','Stone:Vessel-Rim',101,NULL,NULL),
(102,'{\"en\": \"Exists\"}','{\"en\": \"exists\"}','Stone:Vessel-Wall',102,NULL,NULL),
(103,'{\"en\": \"Exists\"}','{\"en\": \"exists\"}','Stone:Vessel-Base',103,NULL,NULL);
*/