
INSERT INTO `glass_base_types` (`id`, `name`) VALUES
(1,'Unassigned'),
(2, 'Vessel/Lamp'),
(3, 'Bead'),
(4, 'Bangle'),
(5, 'Window Glass'),
(6, 'Tbd'),
(7, 'Unknown');

INSERT INTO `tag_types` (`str_id`, `subject`, `category`, `category_order`, `group_order`, `display_name`, `multiple`, `dependency`) VALUES 
/*preservation_id comes here 3.1*/
('Glass:Color','Glass','Characteristics',3,2,'Color',1,NULL),
('Glass:Weathering','Glass','Characteristics',3,5,'Weathering',1,NULL),
('Glass:Weathering-Type','Glass','Characteristics',3,6,'Weathering-Type',1,NULL),
/*base partition comes here 4.1 (base_type_id)*/
('Glass:Vessel-Subtype','Glass','Vessel/Lamp Subtype',5,1,'Vessel/Lamp Subtype',1, '[["L>base_type_id>2"]]'),
('Glass:Production','Glass','Vessel/Lamp Subtype',5,2,'Production',1,'[["L>base_type_id>2"]]');

INSERT INTO `tags` (`id`, `type`, `order_column`, `name`, `created_at`, `updated_at`, `slug`) VALUES 
(6001,'Glass:Color',1,'{"en": "Decolorized"}',NULL,NULL,'{"en": "decolorized"}'),
(6002,'Glass:Color',2,'{"en": "Blue/Green"}',NULL,NULL,'{"en": "blue-green"}'),
(6003,'Glass:Color',3,'{"en": "Cobalt Blue"}',NULL,NULL,'{"en": "Cobalt Blue"}'),
(6004,'Glass:Color',4,'{"en": "Light Blue"}',NULL,NULL,'{"en": "light-blue"}'),
(6005,'Glass:Color',5,'{"en": "Opaque Teal"}',NULL,NULL,'{"en": "opaque-eal"}'),
(6006,'Glass:Color',6,'{"en": "Light Green"}',NULL,NULL,'{"en": "light-reen"}'),
(6007,'Glass:Color',7,'{"en": "Dark Green"}',NULL,NULL,'{"en": "dark-green"}'),
(6008,'Glass:Color',8,'{"en": "Greenish Yellow"}',NULL,NULL,'{"en": "greenish-yellow"}'),
(6009,'Glass:Color',9,'{"en": "Yellow"}',NULL,NULL,'{"en": "yellow"}'),
(6010,'Glass:Color',10,'{"en": "Pinkish-tan"}',NULL,NULL,'{"en": "pinkish-tanl"}'),
(6011,'Glass:Color',11,'{"en": "Brown"}',NULL,NULL,'{"en": "brown"}'),
(6012,'Glass:Color',12,'{"en": "Light Grey"}',NULL,NULL,'{"en": "light-gey"}'),
(6013,'Glass:Color',13,'{"en": "Multicolored"}',NULL,NULL,'{"en": "multicolored"}'),
(6021,'Glass:Production',1,'{"en": "Free Blown"}',NULL,NULL,'{"en": "free-blown"}'),
(6022,'Glass:Production',2,'{"en": "Mold Blown"}',NULL,NULL,'{"en": "mold-blown"}'),
(6023,'Glass:Production',3,'{"en": "Machine Blown"}',NULL,NULL,'{"en": "machine-blown"}'),
(6024,'Glass:Production',4,'{"en": "Machine Pressed"}',NULL,NULL,'{"en": "machine-pressed"}'),
(6025,'Glass:Production',5,'{"en": "Polished"}',NULL,NULL,'{"en": "polished"}'),
(6026,'Glass:Production',6,'{"en": "Incised"}',NULL,NULL,'{"en": "incised"}'),
(6027,'Glass:Production',7,'{"en": "Pontil Mark"}',NULL,NULL,'{"en": "pontil-mark"}'),
(6028,'Glass:Production',8,'{"en": "Plain Decorative Wrap"}',NULL,NULL,'{"en": "plain-decorative-wrap"}'),
(6029,'Glass:Production',9,'{"en": "Twisted Decorative Wrap"}',NULL,NULL,'{"en": "twisted-decorative-wrap"}'),
(6030,'Glass:Production',10,'{"en": "Pinched Wrap"}',NULL,NULL,'{"en": "pinched-wrap"}'),
(6031,'Glass:Production',11,'{"en": "Tool Mark"}',NULL,NULL,'{"en": "tool-mark"}'),
(6041,'Glass:Weathering',1,'{"en": "Very Light"}',NULL,NULL,'{"en": "very-light"}'),
(6042,'Glass:Weathering',2,'{"en": "Light"}',NULL,NULL,'{"en": "light"}'),
(6043,'Glass:Weathering',3,'{"en": "Very Light"}',NULL,NULL,'{"en": "very-light"}'),
(6044,'Glass:Weathering',4,'{"en": "Medium"}',NULL,NULL,'{"en": "medium"}'),
(6045,'Glass:Weathering',5,'{"en": "Heavy"}',NULL,NULL,'{"en": "heavy"}'),
(6046,'Glass:Weathering',6,'{"en": "Very Heavy"}',NULL,NULL,'{"en": "very-heavy"}'),
(6047,'Glass:Weathering',7,'{"en": "Opaque"}',NULL,NULL,'{"en": "opaque"}'),
(6051,'Glass:Weathering-Type',1,'{"en": "Silica Rich Layer"}',NULL,NULL,'{"en": "silica-rich-layer"}'),
(6052,'Glass:Weathering-Type',2,'{"en": "White"}',NULL,NULL,'{"en": "white"}'),
(6053,'Glass:Weathering-Type',3,'{"en": "Black"}',NULL,NULL,'{"en": "black"}'),
(6054,'Glass:Weathering-Type',4,'{"en": "Yellow"}',NULL,NULL,'{"en": "yellow"}'),
(6055,'Glass:Weathering-Type',5,'{"en": "Pitted"}',NULL,NULL,'{"en": "pitted"}'),
(6061,'Glass:Vessel-Subtype',1,'{"en": "Beaker"}',NULL,NULL,'{"en": "Beaker"}'),
(6062,'Glass:Vessel-Subtype',2,'{"en": "Bottle"}',NULL,NULL,'{"en": "Bottle"}'),
(6063,'Glass:Vessel-Subtype',3,'{"en": "Bowl"}',NULL,NULL,'{"en": "bowl"}'),
(6064,'Glass:Vessel-Subtype',4,'{"en": "Cup"}',NULL,NULL,'{"en": "cup"}'),
(6065,'Glass:Vessel-Subtype',5,'{"en": "Dish"}',NULL,NULL,'{"en": "dish"}'),
(6066,'Glass:Vessel-Subtype',6,'{"en": "Footed Cup"}',NULL,NULL,'{"en": "footed-cup"}'),
(6067,'Glass:Vessel-Subtype',7,'{"en": "Goblet"}',NULL,NULL,'{"en": "goblet"}'),
(6068,'Glass:Vessel-Subtype',8,'{"en": "Lamp"}',NULL,NULL,'{"en": "lamp"}'),
(6069,'Glass:Vessel-Subtype',9,'{"en": "Plate"}',NULL,NULL,'{"en": "plate"}'),
(6070,'Glass:Vessel-Subtype',10,'{"en": "Rim"}',NULL,NULL,'{"en": "rim"}'),
(6071,'Glass:Vessel-Subtype',11,'{"en": "Outward Folded Rim"}',NULL,NULL,'{"en": "outward-folded-rim"}'),
(6072,'Glass:Vessel-Subtype',12,'{"en": "Body"}',NULL,NULL,'{"en": "body"}'),
(6073,'Glass:Vessel-Subtype',13,'{"en": "Handle"}',NULL,NULL,'{"en": "handle"}'),
(6074,'Glass:Vessel-Subtype',14,'{"en": "Base"}',NULL,NULL,'{"en": "base"}'),
(6075,'Glass:Vessel-Subtype',15,'{"en": "Hollow Ring Base"}',NULL,NULL,'{"en": "hollow-ring-base"}'),
(6076,'Glass:Vessel-Subtype',16,'{"en": "Solid Ring Base"}',NULL,NULL,'{"en": "solid-ring-base"}');