INSERT INTO `stone_materials` (`id`, `name`) VALUES
(1,'Unassigned'),
(2,'Basalt-vesicular'),
(3,'Basalt-dense'),
(4,'Scoria'),
(5,'Pumice'),
(6,'Limestone'),
(7,'Chalk'),
(8,'Flint or Chert'),
(9,'Sandstone'),
(10,'Granite'),
(11,'amethyst'),
(12,'Steatite'),
(100,'unknown');

INSERT INTO `stone_base_types` (`id`, `name`) VALUES
(1,'Unassigned'),
(2,'Passive'),
(3,'Active (handheld)'),
(4,'Indeterminate Slab or Upper Grinding Stone'),
(5,'Vessel'),
(6,'Non-Processor'),
(7,'Tbd');

INSERT INTO `tag_types` (`str_id`, `subject`, `category`, `category_order`, `group_order`, `display_name`, `multiple`, `dependency`) VALUES 

/*registration comes here 1.1,2... */
/*periods come here 2.1,2...)*/
/*preservation comes here 3.1 (preservation_id)*/
/*material comes here 3.2 (preservation_id)*/
('Stone:Life-Stage','Stone','Basic Characteristics',3,4,'Life Stage',1,NULL),
('Stone:Morphology','Stone','Basic Characteristics',3,5,'Morphology',1,NULL),
('Stone:Profile','Stone','Basic Characteristics',3,6,'Profile',1, NULL),
('Stone:Production','Stone','Basic Characteristics',3,7,'Production',1,NULL),
('Stone:Use-Wear','Stone','Basic Characteristics',3,8,'Use Wear',1,NULL),
/*stone_base_type comes here 5 */
('Stone:Type-Passive','Stone','Typology',8,1,'Passive Subtype',1,'[["L>base_type_id>2"]]'),

('Stone:Type-Active','Stone','Typology',9,5,'Active Subtype',1, '[["L>base_type_id>3"]]'),

('Stone:Vessel-Part','Stone','Typology',10,1,'Vessel Part',1 , '[["L>base_type_id>5"]]'),
('Stone:Vessel-Base','Stone','Typology',10,2,'Vessel Base',1,'[["T>Stone:Vessel-Part>101"]]'),
('Stone:Vessel-Wall','Stone','Typology',10,3,'Vessel Wall',1,'[["T>Stone:Vessel-Part>102"]]'),
('Stone:Vessel-Rim','Stone','Typology',10,4,'Vessel Rim',1,'[["T>Stone:Vessel-Part>103"]]'),

('Stone:Type-Non-Processor','Stone','Typology',10,6,'Non-Processor Subtype',1,'[["L>base_type_id>6"]]');


INSERT INTO `tags` (`id`, `type`, `order_column`, `name`, `created_at`, `updated_at`, `slug`) VALUES
(15,'Stone:Life-Stage',1,'{"en": "Unused"}',NULL,NULL,'{"en": "unused"}'),
(16,'Stone:Life-Stage',2,'{"en": "Blank"}',NULL,NULL,'{"en": "blank"}'),
(17,'Stone:Life-Stage',3,'{"en": "Preform"}',NULL,NULL,'{"en": "preform"}'),
(18,'Stone:Life-Stage',4,'{"en": "Debitage"}',NULL,NULL,'{"en": "debitage"}'),
(19,'Stone:Life-Stage',5,'{"en": "Unfinished"}',NULL,NULL,'{"en": "unfinished"}'),
(20,'Stone:Life-Stage',6,'{"en": "Intentional breakage"}',NULL,NULL,'{"en": "intentional-breakage"}'),
(21,'Stone:Life-Stage',7,'{"en": "Fire-cracked"}',NULL,NULL,'{"en": "fire-cracked"}'),
(22,'Stone:Profile',1,'{"en": "Concave"}',NULL,NULL,'{"en": "concave"}'),
(23,'Stone:Profile',2,'{"en": "Convex"}',NULL,NULL,'{"en": "convex"}'),
(24,'Stone:Profile',3,'{"en": "Flat"}',NULL,NULL,'{"en": "flat"}'),
(25,'Stone:Production',1,'{"en": "Grinding"}',NULL,NULL,'{"en": "grinding"}'),
(26,'Stone:Production',2,'{"en": "Pounding"}',NULL,NULL,'{"en": "pounding"}'),
(27,'Stone:Production',3,'{"en": "Flaking"}',NULL,NULL,'{"en": "flaking"}'),
(28,'Stone:Production',4,'{"en": "Abrading"}',NULL,NULL,'{"en": "abrading"}'),
(29,'Stone:Production',5,'{"en": "Drilling"}',NULL,NULL,'{"en": "drilling"}'),
(30,'Stone:Production',6,'{"en": "Cutting"}',NULL,NULL,'{"en": "cutting"}'),
(31,'Stone:Production',7,'{"en": "Chiseling"}',NULL,NULL,'{"en": "chiseling"}'),
(32,'Stone:Production',8,'{"en": "Polishing"}',NULL,NULL,'{"en": "polishing"}'),
(33,'Stone:Use-Wear',1,'{"en": "Grinding"}',NULL,NULL,'{"en": "grinding"}'),
(34,'Stone:Use-Wear',2,'{"en": "Pounding"}',NULL,NULL,'{"en": "pounding"}'),
(35,'Stone:Use-Wear',3,'{"en": "Flaking"}',NULL,NULL,'{"en": "flaking"}'),
(36,'Stone:Use-Wear',4,'{"en": "Abrading"}',NULL,NULL,'{"en": "abrading"}'),
(37,'Stone:Use-Wear',5,'{"en": "Drilling"}',NULL,NULL,'{"en": "drilling"}'),
(38,'Stone:Use-Wear',6,'{"en": "Residue"}',NULL,NULL,'{"en": "residue"}'),
(39,'Stone:Use-Wear',7,'{"en": "Polish"}',NULL,NULL,'{"en": "polish"}'),
(40,'Stone:Use-Wear',8,'{"en": "Use-light"}',NULL,NULL,'{"en": "use-light"}'),
(41,'Stone:Use-Wear',9,'{"en": "Use-heavy"}',NULL,NULL,'{"en": "use-heavy"}'),
(42,'Stone:Morphology',1,'{"en": "Face-single"}',NULL,NULL,'{"en": "face-single"}'),
(43,'Stone:Morphology',2,'{"en": "Face-multiple"}',NULL,NULL,'{"en": "face-multiple"}'),
(44,'Stone:Morphology',3,'{"en": "Depression"}',NULL,NULL,'{"en": "depression"}'),
(45,'Stone:Morphology',4,'{"en": "Incision"}',NULL,NULL,'{"en": "incision"}'),
(46,'Stone:Morphology',5,'{"en": "Groove or Notch"}',NULL,NULL,'{"en": "groove-or-notch"}'),
(47,'Stone:Morphology',6,'{"en": "Sculpted"}',NULL,NULL,'{"en": "sculpted"}'),
(48,'Stone:Morphology',7,'{"en": "Perforation"}',NULL,NULL,'{"en": "perforation"}'),
(54,'Stone:Type-Passive',1,'{"en": "Grinding Slab"}',NULL,NULL,'{"en": "grinding-slab"}'),
(55,'Stone:Type-Passive',2,'{"en": "Mortar"}',NULL,NULL,'{"en": "mortar"}'),
(56,'Stone:Type-Passive',3,'{"en": "Basin"}',NULL,NULL,'{"en": "basin"}'),
(57,'Stone:Type-Passive',4,'{"en": "Anvil"}',NULL,NULL,'{"en": "anvil"}'),
(58,'Stone:Type-Passive',5,'{"en": "Palette"}',NULL,NULL,'{"en": "palette"}'),
(59,'Stone:Type-Passive',6,'{"en": "Grooved Stone"}',NULL,NULL,'{"en": "grooved-stone"}'),
(60,'Stone:Type-Active',1,'{"en": "Upper Grinding stone"}',NULL,NULL,'{"en": "upper-grinding-stone"}'),
(61,'Stone:Type-Active',2,'{"en": "Pestle"}',NULL,NULL,'{"en": "pestle"}'),
(62,'Stone:Type-Active',3,'{"en": "Grinder"}',NULL,NULL,'{"en": "grinder"}'),
(63,'Stone:Type-Active',4,'{"en": "Pounder"}',NULL,NULL,'{"en": "pounder"}'),
(64,'Stone:Type-Active',5,'{"en": "Abrader"}',NULL,NULL,'{"en": "abrader"}'),
(65,'Stone:Type-Active',6,'{"en": "Scraper"}',NULL,NULL,'{"en": "scraper"}'),
(67,'Stone:Type-Active',7,'{"en": "Multiple-Use"}',NULL,NULL,'{"en": "multiple-use"}'),
(68,'Stone:Type-Active',8,'{"en": "Axe"}',NULL,NULL,'{"en": "axe"}'),
(69,'Stone:Type-Active',9,'{"en": "Hoe"}',NULL,NULL,'{"en": "hoe"}'),
(70,'Stone:Type-Active',10,'{"en": "Digging Stick Weight"}',NULL,NULL,'{"en": "digging-stick-weight"}'),
(72,'Stone:Vessel-Rim',1,'{"en": "Everted"}',NULL,NULL,'{"en": "everted"}'),
(73,'Stone:Vessel-Rim',2,'{"en": "Straight"}',NULL,NULL,'{"en": "straight"}'),
(74,'Stone:Vessel-Rim',3,'{"en": "Inverted"}',NULL,NULL,'{"en": "inverted"}'),
(75,'Stone:Vessel-Wall',1,'{"en": "Convex"}',NULL,NULL,'{"en": "convex"}'),
(76,'Stone:Vessel-Wall',2,'{"en": "Straight"}',NULL,NULL,'{"en": "straight"}'),
(77,'Stone:Vessel-Wall',3,'{"en": "Splayed"}',NULL,NULL,'{"en": "splayed"}'),
(78,'Stone:Vessel-Wall',4,'{"en": "Handle-vertical"}',NULL,NULL,'{"en": "handle-vertical"}'),
(79,'Stone:Vessel-Wall',5,'{"en": "Handle-horizontal"}',NULL,NULL,'{"en": "handle-horizontal"}'),
(80,'Stone:Vessel-Base',1,'{"en": "Flat"}',NULL,NULL,'{"en": "flat"}'),
(81,'Stone:Vessel-Base',2,'{"en": "Rounded"}',NULL,NULL,'{"en": "rounded"}'),
(82,'Stone:Vessel-Base',3,'{"en": "Pedestal"}',NULL,NULL,'{"en": "pedestal"}'),
(83,'Stone:Vessel-Base',4,'{"en": "Footed"}',NULL,NULL,'{"en": "footed"}'),
(84,'Stone:Vessel-Base',5,'{"en": "Fenetsrated"}',NULL,NULL,'{"en": "fenestrated"}'),
(85,'Stone:Vessel-Base',6,'{"en": "Ring"}',NULL,NULL,'{"en": "ring"}'),
(86,'Stone:Vessel-Base',7,'{"en": "Disc"}',NULL,NULL,'{"en": "disc"}'),
(87,'Stone:Type-Non-Processor',1,'{"en": "Architectural"}',NULL,NULL,'{"en": "architectural"}'),
(88,'Stone:Type-Non-Processor',2,'{"en": "Socket"}',NULL,NULL,'{"en": "socket"}'),
(89,'Stone:Type-Non-Processor',3,'{"en": "Stele"}',NULL,NULL,'{"en": "stele"}'),
(91,'Stone:Type-Non-Processor',4,'{"en": "Perforated"}',NULL,NULL,'{"en": "perforated"}'),
(92,'Stone:Type-Non-Processor',5,'{"en": "Tessera"}',NULL,NULL,'{"en": "tessera"}'),
(93,'Stone:Type-Non-Processor',6,'{"en": "Bead"}',NULL,NULL,'{"en": "bead"}'),
(94,'Stone:Type-Non-Processor',7,'{"en": "Figural Art"}',NULL,NULL,'{"en": "figural-art"}'),
(95,'Stone:Type-Non-Processor',8,'{"en": "Worked Stone"}',NULL,NULL,'{"en": "worked-stone"}'),
(96,'Stone:Type-Non-Processor',9,'{"en": "Manuport"}',NULL,NULL,'{"en": "Manuport"}'),
(97,'Stone:Type-Non-Processor',10,'{"en": "Lid"}',NULL,NULL,'{"en": "lid"}'),
(98,'Stone:Type-Non-Processor',11,'{"en": "Pebble or Burnisher"}',NULL,NULL,'{"en": "pebble-or-burnisher"}'),
(100,'Stone:Type-Active',100,'{"en": "Slingstone"}',NULL,NULL,'{"en": "slingstone"}'),
(101,'Stone:Vessel-Part',101,'{"en": "Base"}',NULL,NULL,'{"en": "exists"}'),
(102,'Stone:Vessel-Part',102,'{"en": "Wall"}',NULL,NULL,'{"en": "exists"}'),
(103,'Stone:Vessel-Part',103,'{"en": "Rim"}',NULL,NULL,'{"en": "exists"}'),
(104,'Stone:Type-Non-Processor',98,'{"en": "Scarab"}',NULL,NULL,'{"en": "scarab"}');