INSERT INTO `abouts` (`tag`, `category_index`,`index`, `category_name`, `text`) VALUES
('The Jezreel Expedition',1, 1, 'dig', 'Members of the Jezreel Expedition headed by co-directors Norma Franklin (Zinman Institute of Archaeology, University of Haifa) and Jennie Ebeling (Department of Archaeology and Art History, University of Evansville) conducted an intensive landscape survey of “greater Jezreel” in June 2012. The main goal of the inaugural season was to record surface features in a three square kilometer area to the west, north, and east of Tel Jezreel in order to identify areas for excavation in summer 2013 (Figure 1). The Jezreel team documented more than 360 features, including cisterns, cave tombs, rock-cut tombs, agricultural and industrial installations, terrace and village walls, quarries and more; most of these features had never been systematically recorded before. The results of this survey shed light on the extent of different settlements at Jezreel from late prehistory through to the 20th century CE Palestinian village of Zer’in.'),
('Location',1, 2, 'dig', 'Although the previous excavation project focused on the tel in the Iron Age, various sources suggested that the site was inhabited almost continuously from late prehistory to the modern era. During a foot survey in 2012, and excavations in 2013, the Jezreel Expedition team collected surface pottery dating to the Late Neolithic, Chalcolithic, Early Bronze Age, Intermediate Bronze Age, Iron Age, and Byzantine periods. Cave and cist tombs ranging in date from the Middle Bronze Age to the Byzantine period were documented, as well as architectural elements from the Medieval to the Ottoman period; all testifying to the uninterrupted existence of Jezreel in the longue dureé.'),
('Tell Ein-Jezreel',1, 3, 'dig', 'Co-Directors: Dr. Norma Franklin (University of Haifa) and Dr. Jennie Ebeling (University of Evansville)'),
('Earlier Research',1, 4, 'dig', 'Although the previous excavation project focused on the tel in the Iron Age, various sources suggested that the site was inhabited almost continuously from late prehistory to the modern era. During a foot survey in 2012, and excavations in 2013, the Jezreel Expedition team collected surface pottery dating to the Late Neolithic, Chalcolithic, Early Bronze Age, Intermediate Bronze Age, Iron Age, and Byzantine periods. Cave and cist tombs ranging in date from the Middle Bronze Age to the Byzantine period were documented, as well as architectural elements from the Medieval to the Ottoman period; all testifying to the uninterrupted existence of Jezreel in the longue dureé.'),
('Goals',1, 5, 'dig', 'Although the previous excavation project focused on the tel in the Iron Age, various sources suggested that the site was inhabited almost continuously from late prehistory to the modern era. During a foot survey in 2012, and excavations in 2013, the Jezreel Expedition team collected surface pottery dating to the Late Neolithic, Chalcolithic, Early Bronze Age, Intermediate Bronze Age, Iron Age, and Byzantine periods. Cave and cist tombs ranging in date from the Middle Bronze Age to the Byzantine period were documented, as well as architectural elements from the Medieval to the Ottoman period; all testifying to the uninterrupted existence of Jezreel in the longue dureé.'),
('This website',2, 1, 'db', 'This website displays the results of the Jezreel-Expedition finds'),
('Goals',2, 2, 'db', 'This website displays the results of the Jezreel-Expedition finds'),
('Basic Design',2, 3, 'db', 'This website displays the results of the Jezreel-Expedition finds'),
('Technical Details',2, 4, 'db', 'This website displays the results of the Jezreel-Expedition finds');



