INSERT INTO `tag_types` (`str_id`, `name_major`, `name_minor`, `display_name`, `multiple`, `order_column`, `dependency`) VALUES 
('Glass:Color','Glass','Color','Color',1,204,NULL),
('Glass:Production','Glass','Production','Production',1,23,NULL),
('Glass:Vessel-Subtype','Glass','Vessel-Subtype','Vessel/Lamp Subtype',1,22,'{"field_name": "base_type_id", "param_name": "Vessel/Lamp", "depends_on_tag": false}'),
('Glass:Weathering','Glass','Weathering','Weathering',1,205,NULL),
('Glass:Weathering-Type','Glass','Weathering-Type','Weathering-Type',1,206,NULL),

('Periods:Base-Type','Period','Base-Type','Periods (Top-Level)',1,501,NULL),
('Periods:Bronze','Period','Bronze','Bronze Subperiods',1,506,'{"tag_name": "Bronze", "tag_type_name": "Periods:Base-Type", "depends_on_tag": true}'),
/*('Periods:Byzantine','Period','Byzantine','Byzantine Subperiods',1,511,'{"tag_name": "Byzantine", "tag_type_name": "Periods:Base-Type", "depends_on_tag": true}'),*/
/*('Periods:Chalcolithic','Period','Chalcolithic','Chalcolithic Subperiods',1,505,'{"tag_name": "Chalcolithic", "tag_type_name": "Periods:Base-Type", "depends_on_tag": true}'),*/
('Periods:Early-Islamic','Period','Early-Islamic','Early-Islamic Subperiods',1,512,'{"tag_name": "Early Islamic", "tag_type_name": "Periods:Base-Type", "depends_on_tag": true}'),
/*('Periods:Epipaleolithic','Period','Epipaleolithic','Epipaleolithic Subperiods',1,503,'{"tag_name": "Epipaleolithic", "tag_type_name": "Periods:Base-Type", "depends_on_tag": true}'),*/
('Periods:Hellenistic','Period','Hellenistic','Hellenistic Subperiods',1,509,'{"tag_name": "Hellenistic", "tag_type_name": "Periods:Base-Type", "depends_on_tag": true}'),
('Periods:Iron','Period','Iron','Iron Subperiods',1,507,'{"tag_name": "Iron", "tag_type_name": "Periods:Base-Type", "depends_on_tag": true}'),
('Periods:Medieval','Period','Medieval','Medieval Subperiods',1,513,'{"tag_name": "Medieval", "tag_type_name": "Periods:Base-Type", "depends_on_tag": true}'),
('Periods:Modern','Period','Modern','Modern Subperiods',1,515,'{"tag_name": "Modern", "tag_type_name": "Periods:Base-Type", "depends_on_tag": true}'),
('Periods:Neolithic','Period','Neolithic','Neolithic Subperiods',1,504,'{"tag_name": "Neolithic", "tag_type_name": "Periods:Base-Type", "depends_on_tag": true}'),
/*('Periods:Ottoman','Period','Ottoman','Ottoman Subperiods',1,514,'{"tag_name": "Ottoman", "tag_type_name": "Periods:Base-Type", "depends_on_tag": true}'),*/
/*('Periods:Paleolithic','Period','Paleolithic','Paleolithic Subperiods',1,502,'{"tag_name": "Paleolithic", "tag_type_name": "Periods:Base-Type", "depends_on_tag": true}'),*/
/*('Periods:Persian','Period','Persian','Persian Subperiods',1,508,'{"tag_name": "Persian", "tag_type_name": "Periods:Base-Type", "depends_on_tag": true}'),*/
('Periods:Roman','Period','Roman','Roman Subperiods',1,510,'{"tag_name": "Roman", "tag_type_name": "Periods:Base-Type", "depends_on_tag": true}'),

('Stone:Life-Stage','Stone','Life-Stage','Life Stage',1,10,NULL),
('Stone:Morphology','Stone','Morphology','Morphology',1,11,NULL),
('Stone:Production','Stone','Production','Production',1,13,NULL),
('Stone:Profile','Stone','Profile','Profile',1,12,NULL),
('Stone:Type-Active','Stone','Type-Active','Active Subtype',1,2,'{"field_name": "base_type_id", "param_name": "Active (handheld)", "depends_on_tag": false}'),
('Stone:Type-Non-Processor','Stone','Type-Non-Processor','Non-Processor Subtype',1,3,'{"field_name": "base_type_id", "param_name": "Non-Processor", "depends_on_tag": false}'),
('Stone:Type-Passive','Stone','Type-Passive','Passive Subtype',1,1,'{"field_name": "base_type_id", "param_name": "Passive", "depends_on_tag": false}'),
('Stone:Use-Wear','Stone','Use-Wear','Use Wear',1,14,NULL),
('Stone:Vessel-Base','Stone','Base','Vessel Base',1,6,'{"field_name": "base_type_id", "param_name": "Vessel", "depends_on_tag": false}'),
('Stone:Vessel-Rim','Stone','Rim','Vessel Rim',1,4,'{"field_name": "base_type_id", "param_name": "Vessel", "depends_on_tag": false}'),
('Stone:Vessel-Wall','Stone','Wall','Vessel Wall',1,5,'{"field_name": "base_type_id", "param_name": "Vessel", "depends_on_tag": false}'),

/*('Pottery:Fabric','Pottery','Fabric','Fabric',1,1,NULL),
('Pottery:Fabric-Color','Pottery','Fabric-Color','Fabric Color',1,2,NULL),
('Pottery:Common-Types','Pottery','Common-Types','Common-Types',1,1,NULL),*/
('Pottery:Life-Stage','Pottery','Life-Stage','Life Stage',1,3,NULL),
('Pottery:Forming-Technique','Pottery','Forming-Technique','Forming-Technique',1,4,NULL),
('Pottery:Surface-Treatment','Pottery','Surface-Treatment','Surface-Treatment',1,5,NULL),

('Pottery:Vessel-Subtype','Pottery','Vessel-Subtype','Vessel Subtype',1,6,'{"field_name": "base_type_id", "param_name": "Vessel", "depends_on_tag": false}'),
('Pottery:Part','Pottery','Part','Vessel Part',1,7,'{"field_name": "base_type_id", "param_name": "Vessel", "depends_on_tag": false}'),
('Pottery:Handle','Pottery','Handle-Type','Handle-Type',1,8,'{"tag_name": "Handle", "tag_type_name": "Pottery:Part", "depends_on_tag": true}'),
('Pottery:Base','Pottery','Base-Type','Base-Type',1,9,'{"tag_name": "Base", "tag_type_name": "Pottery:Part", "depends_on_tag": true}'),
('Pottery:Non-Vessel-Subtype','Pottery','Non-Vessel-Subtype','Non-Vessel-Subtype',1,10,'{"field_name": "base_type_id", "param_name": "Non-Vessel", "depends_on_tag": false}');


INSERT INTO `tags` (`id`, `name`, `slug`, `type`, `order_column`, `created_at`, `updated_at`) VALUES
/*
(501,'{"en": "Coarse Ware"}','{"en": ""}','Pottery:Fabric',1,NULL,NULL),
(502,'{"en": "Semi-Fine Ware"}','{"en": ""}','Pottery:Fabric',2,NULL,NULL),
(503,'{"en": "Fine Ware"}','{"en": ""}','Pottery:Fabric',3,NULL,NULL),

(510,'{"en": "Yellow"}','{"en": ""}','Pottery:Fabric-Color',1,NULL,NULL),
(511,'{"en": "Brown"}','{"en": ""}','Pottery:Fabric-Color',2,NULL,NULL),
(512,'{"en": "Red"}','{"en": ""}','Pottery:Fabric-Color',3,NULL,NULL),
(513,'{"en": "Grey"}','{"en": ""}','Pottery:Fabric-Color',4,NULL,NULL),
(514,'{"en": "Yellow"}','{"en": ""}','Pottery:Fabric-Color',5,NULL,NULL),
(515,'{"en": "Black"}','{"en": ""}','Pottery:Fabric-Color',6,NULL,NULL),
*/


(15,'{"en": "Unused"}','{"en": "unused"}','Stone:Life-Stage',15,NULL,NULL),
(16,'{"en": "Blank"}','{"en": "blank"}','Stone:Life-Stage',16,NULL,NULL),
(17,'{"en": "Preform"}','{"en": "preform"}','Stone:Life-Stage',17,NULL,NULL),
(18,'{"en": "Debitage"}','{"en": "debitage"}','Stone:Life-Stage',18,NULL,NULL),
(19,'{"en": "Unfinished"}','{"en": "unfinished"}','Stone:Life-Stage',19,NULL,NULL),
(20,'{"en": "Intentional breakage"}','{"en": "intentional-breakage"}','Stone:Life-Stage',20,NULL,NULL),
(21,'{"en": "Fire-cracked"}','{"en": "fire-cracked"}','Stone:Life-Stage',21,NULL,NULL),
(22,'{"en": "Concave"}','{"en": "concave"}','Stone:Profile',22,NULL,NULL),
(23,'{"en": "Convex"}','{"en": "convex"}','Stone:Profile',23,NULL,NULL),
(24,'{"en": "Flat"}','{"en": "flat"}','Stone:Profile',24,NULL,NULL),
(25,'{"en": "Grinding"}','{"en": "grinding"}','Stone:Production',25,NULL,NULL),
(26,'{"en": "Pounding"}','{"en": "pounding"}','Stone:Production',26,NULL,NULL),
(27,'{"en": "Flaking"}','{"en": "flaking"}','Stone:Production',27,NULL,NULL),
(28,'{"en": "Abrading"}','{"en": "abrading"}','Stone:Production',28,NULL,NULL),
(29,'{"en": "Drilling"}','{"en": "drilling"}','Stone:Production',29,NULL,NULL),
(30,'{"en": "Cutting"}','{"en": "cutting"}','Stone:Production',30,NULL,NULL),
(31,'{"en": "Chiseling"}','{"en": "chiseling"}','Stone:Production',31,NULL,NULL),
(32,'{"en": "Polishing"}','{"en": "polishing"}','Stone:Production',32,NULL,NULL),
(33,'{"en": "Grinding"}','{"en": "grinding"}','Stone:Use-Wear',33,NULL,NULL),
(34,'{"en": "Pounding"}','{"en": "pounding"}','Stone:Use-Wear',34,NULL,NULL),
(35,'{"en": "Flaking"}','{"en": "flaking"}','Stone:Use-Wear',35,NULL,NULL),
(36,'{"en": "Abrading"}','{"en": "abrading"}','Stone:Use-Wear',36,NULL,NULL),
(37,'{"en": "Drilling"}','{"en": "drilling"}','Stone:Use-Wear',37,NULL,NULL),
(38,'{"en": "Residue"}','{"en": "residue"}','Stone:Use-Wear',38,NULL,NULL),
(39,'{"en": "Polish"}','{"en": "polish"}','Stone:Use-Wear',39,NULL,NULL),
(40,'{"en": "Use-light"}','{"en": "use-light"}','Stone:Use-Wear',40,NULL,NULL),
(41,'{"en": "Use-heavy"}','{"en": "use-heavy"}','Stone:Use-Wear',41,NULL,NULL),
(42,'{"en": "Face-single"}','{"en": "face-single"}','Stone:Morphology',42,NULL,NULL),
(43,'{"en": "Face-multiple"}','{"en": "face-multiple"}','Stone:Morphology',43,NULL,NULL),
(44,'{"en": "Depression"}','{"en": "depression"}','Stone:Morphology',44,NULL,NULL),
(45,'{"en": "Incision"}','{"en": "incision"}','Stone:Morphology',45,NULL,NULL),
(46,'{"en": "Groove or Notch"}','{"en": "groove-or-notch"}','Stone:Morphology',46,NULL,NULL),
(47,'{"en": "Sculpted"}','{"en": "sculpted"}','Stone:Morphology',47,NULL,NULL),
(48,'{"en": "Perforation"}','{"en": "perforation"}','Stone:Morphology',48,NULL,NULL),
(54,'{"en": "Grinding Slab"}','{"en": "grinding-slab"}','Stone:Type-Passive',54,NULL,NULL),
(55,'{"en": "Mortar"}','{"en": "mortar"}','Stone:Type-Passive',55,NULL,NULL),
(56,'{"en": "Basin"}','{"en": "basin"}','Stone:Type-Passive',56,NULL,NULL),
(57,'{"en": "Anvil"}','{"en": "anvil"}','Stone:Type-Passive',57,NULL,NULL),
(58,'{"en": "Palette"}','{"en": "palette"}','Stone:Type-Passive',58,NULL,NULL),
(59,'{"en": "Grooved Stone"}','{"en": "grooved-stone"}','Stone:Type-Passive',59,NULL,NULL),
(60,'{"en": "Upper Grinding stone"}','{"en": "upper-grinding-stone"}','Stone:Type-Active',60,NULL,NULL),
(61,'{"en": "Pestle"}','{"en": "pestle"}','Stone:Type-Active',61,NULL,NULL),
(62,'{"en": "Grinder"}','{"en": "grinder"}','Stone:Type-Active',62,NULL,NULL),
(63,'{"en": "Pounder"}','{"en": "pounder"}','Stone:Type-Active',63,NULL,NULL),
(64,'{"en": "Abrader"}','{"en": "abrader"}','Stone:Type-Active',64,NULL,NULL),
(65,'{"en": "Scraper"}','{"en": "scraper"}','Stone:Type-Active',65,NULL,NULL),
(67,'{"en": "Multiple-Use"}','{"en": "multiple-use"}','Stone:Type-Active',67,NULL,NULL),
(68,'{"en": "Axe"}','{"en": "axe"}','Stone:Type-Active',68,NULL,NULL),
(69,'{"en": "Hoe"}','{"en": "hoe"}','Stone:Type-Active',69,NULL,NULL),
(70,'{"en": "Digging Stick Weight"}','{"en": "digging-stick-weight"}','Stone:Type-Active',70,NULL,NULL),
(72,'{"en": "Everted"}','{"en": "everted"}','Stone:Vessel-Rim',72,NULL,NULL),
(73,'{"en": "Straight"}','{"en": "straight"}','Stone:Vessel-Rim',73,NULL,NULL),
(74,'{"en": "Inverted"}','{"en": "inverted"}','Stone:Vessel-Rim',74,NULL,NULL),
(75,'{"en": "Convex"}','{"en": "convex"}','Stone:Vessel-Wall',75,NULL,NULL),
(76,'{"en": "Straight"}','{"en": "straight"}','Stone:Vessel-Wall',76,NULL,NULL),
(77,'{"en": "Splayed"}','{"en": "splayed"}','Stone:Vessel-Wall',77,NULL,NULL),
(78,'{"en": "Handle-vertical"}','{"en": "handle-vertical"}','Stone:Vessel-Wall',78,NULL,NULL),
(79,'{"en": "Handle-horizontal"}','{"en": "handle-horizontal"}','Stone:Vessel-Wall',79,NULL,NULL),
(80,'{"en": "Flat"}','{"en": "flat"}','Stone:Vessel-Base',80,NULL,NULL),
(81,'{"en": "Rounded"}','{"en": "rounded"}','Stone:Vessel-Base',81,NULL,NULL),
(82,'{"en": "Pedestal"}','{"en": "pedestal"}','Stone:Vessel-Base',82,NULL,NULL),
(83,'{"en": "Footed"}','{"en": "footed"}','Stone:Vessel-Base',83,NULL,NULL),
(84,'{"en": "Fenetsrated"}','{"en": "fenestrated"}','Stone:Vessel-Base',84,NULL,NULL),
(85,'{"en": "Ring"}','{"en": "ring"}','Stone:Vessel-Base',85,NULL,NULL),
(86,'{"en": "Disc"}','{"en": "disc"}','Stone:Vessel-Base',86,NULL,NULL),
(87,'{"en": "Architectural"}','{"en": "architectural"}','Stone:Type-Non-Processor',87,NULL,NULL),
(88,'{"en": "Socket"}','{"en": "socket"}','Stone:Type-Non-Processor',88,NULL,NULL),
(89,'{"en": "Stele"}','{"en": "stele"}','Stone:Type-Non-Processor',89,NULL,NULL),
(91,'{"en": "Perforated"}','{"en": "perforated"}','Stone:Type-Non-Processor',91,NULL,NULL),
(92,'{"en": "Tessera"}','{"en": "tessera"}','Stone:Type-Non-Processor',92,NULL,NULL),
(93,'{"en": "Bead"}','{"en": "bead"}','Stone:Type-Non-Processor',93,NULL,NULL),
(94,'{"en": "Figural Art"}','{"en": "figural-art"}','Stone:Type-Non-Processor',94,NULL,NULL),
(95,'{"en": "Worked Stone"}','{"en": "worked-stone"}','Stone:Type-Non-Processor',95,NULL,NULL),
(96,'{"en": "Manuport"}','{"en": "Manuport"}','Stone:Type-Non-Processor',96,NULL,NULL),
(97,'{"en": "Lid"}','{"en": "lid"}','Stone:Type-Non-Processor',97,NULL,NULL),
(98,'{"en": "Pebble or Burnisher"}','{"en": "pebble-or-burnisher"}','Stone:Type-Non-Processor',98,NULL,NULL),
(100,'{"en": "Slingstone"}','{"en": "slingstone"}','Stone:Type-Active',100,NULL,NULL),
(101,'{"en": "Exists"}','{"en": "exists"}','Stone:Vessel-Rim',101,NULL,NULL),
(102,'{"en": "Exists"}','{"en": "exists"}','Stone:Vessel-Wall',102,NULL,NULL),
(103,'{"en": "Exists"}','{"en": "exists"}','Stone:Vessel-Base',103,NULL,NULL),
(104,'{"en": "Scarab"}','{"en": "scarab"}','Stone:Type-Non-Processor',98,NULL,NULL),

(201,'{"en": "Decolorized"}','{"en": "decolorized"}','Glass:Color',1,NULL,NULL),
(202,'{"en": "Blue/Green"}','{"en": "blue-green"}','Glass:Color',2,NULL,NULL),
(203,'{"en": "Cobalt Blue"}','{"en": "Cobalt Blue"}','Glass:Color',3,NULL,NULL),
(204,'{"en": "Light Blue"}','{"en": "light-blue"}','Glass:Color',4,NULL,NULL),
(205,'{"en": "Opaque Teal"}','{"en": "opaque-eal"}','Glass:Color',5,NULL,NULL),
(206,'{"en": "Light Green"}','{"en": "light-reen"}','Glass:Color',6,NULL,NULL),
(207,'{"en": "Dark Green"}','{"en": "dark-green"}','Glass:Color',7,NULL,NULL),
(208,'{"en": "Greenish Yellow"}','{"en": "greenish-yellow"}','Glass:Color',8,NULL,NULL),
(209,'{"en": "Yellow"}','{"en": "yellow"}','Glass:Color',9,NULL,NULL),
(210,'{"en": "Pinkish-tan"}','{"en": "pinkish-tanl"}','Glass:Color',10,NULL,NULL),
(211,'{"en": "Brown"}','{"en": "brown"}','Glass:Color',11,NULL,NULL),
(212,'{"en": "Light Grey"}','{"en": "light-gey"}','Glass:Color',12,NULL,NULL),
(213,'{"en": "Multicolored"}','{"en": "multicolored"}','Glass:Color',13,NULL,NULL),

(221,'{"en": "Free Blown"}','{"en": "free-blown"}','Glass:Production',1,NULL,NULL),
(222,'{"en": "Mold Blown"}','{"en": "mold-blown"}','Glass:Production',2,NULL,NULL),
(223,'{"en": "Machine Blown"}','{"en": "machine-blown"}','Glass:Production',3,NULL,NULL),
(224,'{"en": "Machine Pressed"}','{"en": "machine-pressed"}','Glass:Production',4,NULL,NULL),
(225,'{"en": "Polished"}','{"en": "polished"}','Glass:Production',5,NULL,NULL),
(226,'{"en": "Incised"}','{"en": "incised"}','Glass:Production',6,NULL,NULL),
(227,'{"en": "Pontil Mark"}','{"en": "pontil-mark"}','Glass:Production',7,NULL,NULL),
(228,'{"en": "Plain Decorative Wrap"}','{"en": "plain-decorative-wrap"}','Glass:Production',8,NULL,NULL),
(229,'{"en": "Twisted Decorative Wrap"}','{"en": "twisted-decorative-wrap"}','Glass:Production',9,NULL,NULL),
(230,'{"en": "Pinched Wrap"}','{"en": "pinched-wrap"}','Glass:Production',10,NULL,NULL),
(231,'{"en": "Tool Mark"}','{"en": "tool-mark"}','Glass:Production',11,NULL,NULL),

(241,'{"en": "Very Light"}','{"en": "very-light"}','Glass:Weathering',1,NULL,NULL),
(242,'{"en": "Light"}','{"en": "light"}','Glass:Weathering',2,NULL,NULL),
(243,'{"en": "Very Light"}','{"en": "very-light"}','Glass:Weathering',3,NULL,NULL),
(244,'{"en": "Medium"}','{"en": "medium"}','Glass:Weathering',4,NULL,NULL),
(245,'{"en": "Heavy"}','{"en": "heavy"}','Glass:Weathering',5,NULL,NULL),
(246,'{"en": "Very Heavy"}','{"en": "very-heavy"}','Glass:Weathering',6,NULL,NULL),
(247,'{"en": "Opaque"}','{"en": "opaque"}','Glass:Weathering',7,NULL,NULL),

(251,'{"en": "Silica Rich Layer"}','{"en": "silica-rich-layer"}','Glass:Weathering-Type',1,NULL,NULL),
(252,'{"en": "White"}','{"en": "white"}','Glass:Weathering-Type',2,NULL,NULL),
(253,'{"en": "Black"}','{"en": "black"}','Glass:Weathering-Type',3,NULL,NULL),
(254,'{"en": "Yellow"}','{"en": "yellow"}','Glass:Weathering-Type',4,NULL,NULL),
(255,'{"en": "Pitted"}','{"en": "pitted"}','Glass:Weathering-Type',5,NULL,NULL),

(261,'{"en": "Beaker"}','{"en": "Beaker"}','Glass:Vessel-Subtype',1,NULL,NULL),
(262,'{"en": "Bottle"}','{"en": "Bottle"}','Glass:Vessel-Subtype',2,NULL,NULL),
(263,'{"en": "Bowl"}','{"en": "bowl"}','Glass:Vessel-Subtype',3,NULL,NULL),
(264,'{"en": "Cup"}','{"en": "cup"}','Glass:Vessel-Subtype',4,NULL,NULL),
(265,'{"en": "Dish"}','{"en": "dish"}','Glass:Vessel-Subtype',5,NULL,NULL),
(266,'{"en": "Footed Cup"}','{"en": "footed-cup"}','Glass:Vessel-Subtype',6,NULL,NULL),
(267,'{"en": "Goblet"}','{"en": "goblet"}','Glass:Vessel-Subtype',7,NULL,NULL),
(268,'{"en": "Lamp"}','{"en": "lamp"}','Glass:Vessel-Subtype',8,NULL,NULL),
(269,'{"en": "Plate"}','{"en": "plate"}','Glass:Vessel-Subtype',9,NULL,NULL),
(270,'{"en": "Rim"}','{"en": "rim"}','Glass:Vessel-Subtype',10,NULL,NULL),
(271,'{"en": "Outward Folded Rim"}','{"en": "outward-folded-rim"}','Glass:Vessel-Subtype',11,NULL,NULL),
(272,'{"en": "Body"}','{"en": "body"}','Glass:Vessel-Subtype',12,NULL,NULL),
(273,'{"en": "Handle"}','{"en": "handle"}','Glass:Vessel-Subtype',13,NULL,NULL),
(274,'{"en": "Base"}','{"en": "base"}','Glass:Vessel-Subtype',14,NULL,NULL),
(275,'{"en": "Hollow Ring Base"}','{"en": "hollow-ring-base"}','Glass:Vessel-Subtype',15,NULL,NULL),
(276,'{"en": "Solid Ring Base"}','{"en": "solid-ring-base"}','Glass:Vessel-Subtype',16,NULL,NULL),


(521,'{"en": "Unfired"}','{"en": ""}','Pottery:Life-Stage',1,NULL,NULL),

(523,'{"en": "Reworked Sherd Unperforated"}','{"en": ""}','Pottery:Life-Stage',3,NULL,NULL),
(524,'{"en": "Reworked Sherd Drilled One Side"}','{"en": ""}','Pottery:Life-Stage',4,NULL,NULL),
(525,'{"en": "Reworked Sherd Perforated"}','{"en": ""}','Pottery:Life-Stage',4,NULL,NULL),
(532,'{"en": "Coil"}','{"en": ""}','Pottery:Forming-Technique',2,NULL,NULL),
(533,'{"en": "Slab"}','{"en": ""}','Pottery:Forming-Technique',3,NULL,NULL),
(534,'{"en": "Mat"}','{"en": ""}','Pottery:Forming-Technique',4,NULL,NULL),
(531,'{"en": "Wheel"}','{"en": ""}','Pottery:Forming-Technique',1,NULL,NULL),



(541,'{"en": "Burnish"}','{"en": ""}','Pottery:Surface-Treatment',1,NULL,NULL),
(542,'{"en": "Slip"}','{"en": ""}','Pottery:Surface-Treatment',2,NULL,NULL),
(543,'{"en": "Glaze"}','{"en": ""}','Pottery:Surface-Treatment',3,NULL,NULL),
(544,'{"en": "Paint"}','{"en": ""}','Pottery:Surface-Treatment',4,NULL,NULL),
(545,'{"en": "Punctation"}','{"en": ""}','Pottery:Surface-Treatment',5,NULL,NULL),
(546,'{"en": "Incision"}','{"en": ""}','Pottery:Surface-Treatment',6,NULL,NULL),

(551,'{"en": "Funnel"}','{"en": ""}','Pottery:Non-Vessel-Subtype',1,NULL,NULL),
(552,'{"en": "Baking Tray"}','{"en": ""}','Pottery:Non-Vessel-Subtype',2,NULL,NULL),
(553,'{"en": "Strainer"}','{"en": ""}','Pottery:Non-Vessel-Subtype',3,NULL,NULL),
(554,'{"en": "Stand"}','{"en": ""}','Pottery:Non-Vessel-Subtype',4,NULL,NULL),
(555,'{"en": "Lamp"}','{"en": ""}','Pottery:Non-Vessel-Subtype',5,NULL,NULL),
(556,'{"en": "Cup and Saucer"}','{"en": ""}','Pottery:Non-Vessel-Subtype',6,NULL,NULL),
(557,'{"en": "Pipe"}','{"en": ""}','Pottery:Non-Vessel-Subtype',7,NULL,NULL),

(561,'{"en": "Bowl"}','{"en": ""}','Pottery:Vessel-Subtype',1,NULL,NULL),
(562,'{"en": "Scoop"}','{"en": ""}','Pottery:Vessel-Subtype',2,NULL,NULL),
(563,'{"en": "Chalice"}','{"en": ""}','Pottery:Vessel-Subtype',3,NULL,NULL),
(564,'{"en": "Goblet"}','{"en": ""}','Pottery:Vessel-Subtype',4,NULL,NULL),
(565,'{"en": "Krater"}','{"en": ""}','Pottery:Vessel-Subtype',5,NULL,NULL),
(566,'{"en": "Cooking Pot"}','{"en": ""}','Pottery:Vessel-Subtype',6,NULL,NULL),
(567,'{"en": "Pithos"}','{"en": ""}','Pottery:Vessel-Subtype',7,NULL,NULL),
(568,'{"en": "Storage Jar"}','{"en": ""}','Pottery:Vessel-Subtype',8,NULL,NULL),
(569,'{"en": "Amphora"}','{"en": ""}','Pottery:Vessel-Subtype',9,NULL,NULL),
(570,'{"en": "Jug"}','{"en": ""}','Pottery:Vessel-Subtype',10,NULL,NULL),
(571,'{"en": "Juglet"}','{"en": ""}','Pottery:Vessel-Subtype',11,NULL,NULL),
(572,'{"en": "Bottle"}','{"en": ""}','Pottery:Vessel-Subtype',12,NULL,NULL),
(573,'{"en": "Pyxide"}','{"en": ""}','Pottery:Vessel-Subtype',13,NULL,NULL),
(574,'{"en": "Flask"}','{"en": ""}','Pottery:Vessel-Subtype',14,NULL,NULL),
(575,'{"en": "Pithos"}','{"en": ""}','Pottery:Vessel-Subtype',15,NULL,NULL),

/*(590,'{"en": "Rim"}','{"en": ""}','Pottery:Part',4,NULL,NULL),*/

(591,'{"en": "Base"}','{"en": ""}','Pottery:Part',1,NULL,NULL),
(592,'{"en": "Handle"}','{"en": ""}','Pottery:Part',2,NULL,NULL),
(593,'{"en": "Spout"}','{"en": ""}','Pottery:Part',3,NULL,NULL),


(600,'{"en": "Handle type A"}','{"en": ""}','Pottery:Handle',1,NULL,NULL),
(601,'{"en": "Handle type B"}','{"en": ""}','Pottery:Handle',2,NULL,NULL),
(602,'{"en": "Handle type C"}','{"en": ""}','Pottery:Handle',3,NULL,NULL),
(610,'{"en": "Base type A"}','{"en": ""}','Pottery:Base',1,NULL,NULL),
(611,'{"en": "Base type B"}','{"en": ""}','Pottery:Base',2,NULL,NULL),
(612,'{"en": "Base type C"}','{"en": ""}','Pottery:Base',3,NULL,NULL),

/*
(651,'{"en": "Khirbet Kerak"}','{"en": ""}','Pottery:Common-Types',1,NULL,NULL),
(652,'{"en": "Chocolate-on-white"}','{"en": ""}','Pottery:Common-Types',2,NULL,NULL),
(653,'{"en": "Bichrome Ware"}','{"en": ""}','Pottery:Common-Types',3,NULL,NULL),
(654,'{"en": "Mycenaean"}','{"en": ""}','Pottery:Common-Types',4,NULL,NULL),
(655,'{"en": "Philistine Bichrome"}','{"en": ""}','Pottery:Common-Types',5,NULL,NULL),
(656,'{"en": "Roman Cooking Pot"}','{"en": ""}','Pottery:Common-Types',6,NULL,NULL),
*/




(5102,'{"en": "Paleolithic"}','{"en": "Paleolithic"}','Periods:Base-Type',5002,NULL,NULL),
(5103,'{"en": "Epipaleolithic"}','{"en": "Epipaleolithic"}','Periods:Base-Type',5003,NULL,NULL),
(5104,'{"en": "Neolithic"}','{"en": "Neolithic"}','Periods:Base-Type',5004,NULL,NULL),
(5105,'{"en": "Chalcolithic"}','{"en": "Chalcolithic"}','Periods:Base-Type',5005,NULL,NULL),
(5106,'{"en": "Bronze"}','{"en": "Bronze"}','Periods:Base-Type',5006,NULL,NULL),
(5107,'{"en": "Iron"}','{"en": "Iron"}','Periods:Base-Type',5007,NULL,NULL),
(5108,'{"en": "Persian"}','{"en": "Persian"}','Periods:Base-Type',5008,NULL,NULL),
(5109,'{"en": "Hellenistic"}','{"en": "Hellenistic"}','Periods:Base-Type',5009,NULL,NULL),
(5110,'{"en": "Roman"}','{"en": "Roman"}','Periods:Base-Type',5010,NULL,NULL),
(5111,'{"en": "Byzantine"}','{"en": "Byzantine"}','Periods:Base-Type',5011,NULL,NULL),
(5112,'{"en": "Early Islamic"}','{"en": "Early Islamic"}','Periods:Base-Type',5012,NULL,NULL),
(5113,'{"en": "Medieval"}','{"en": "Medieval"}','Periods:Base-Type',5013,NULL,NULL),
(5114,'{"en": "Ottoman"}','{"en": "Ottoman"}','Periods:Base-Type',5014,NULL,NULL),
(5115,'{"en": "Modern"}','{"en": "Modern"}','Periods:Base-Type',5015,NULL,NULL),
(5401,'{"en": "PPNA"}','{"en": "PPNA"}','Periods:Neolithic',5401,NULL,NULL),
(5402,'{"en": "PPNB"}','{"en": "PPNB"}','Periods:Neolithic',5402,NULL,NULL),
(5403,'{"en": "PPNC"}','{"en": "PPNC"}','Periods:Neolithic',5403,NULL,NULL),
(5404,'{"en": "Pottery Neolithic"}','{"en": "Pottery Neolithic"}','Periods:Neolithic',5404,NULL,NULL),
(5405,'{"en": "Yarmukian"}','{"en": "Yarmukian"}','Periods:Neolithic',5405,NULL,NULL),
(5406,'{"en": "Wadi Rabah"}','{"en": "Wadi Rabah"}','Periods:Neolithic',5406,NULL,NULL),
(5601,'{"en": "EB"}','{"en": "EB"}','Periods:Bronze',5601,NULL,NULL),
(5602,'{"en": "EB I"}','{"en": "EB I"}','Periods:Bronze',5602,NULL,NULL),
(5603,'{"en": "EB II"}','{"en": "EB II"}','Periods:Bronze',5603,NULL,NULL),
(5604,'{"en": "EB III"}','{"en": "EB III"}','Periods:Bronze',5604,NULL,NULL),
(5605,'{"en": "IB"}','{"en": "IB"}','Periods:Bronze',5605,NULL,NULL),
(5606,'{"en": "MB"}','{"en": "MB"}','Periods:Bronze',5606,NULL,NULL),
(5608,'{"en": "MB IIA"}','{"en": "MB IIA"}','Periods:Bronze',5608,NULL,NULL),
(5609,'{"en": "MB IIB"}','{"en": "MB IIB"}','Periods:Bronze',5609,NULL,NULL),
(5610,'{"en": "MB IIC"}','{"en": "MB IIC"}','Periods:Bronze',5610,NULL,NULL),
(5611,'{"en": "LB"}','{"en": "LB"}','Periods:Bronze',5611,NULL,NULL),
(5612,'{"en": "LB I"}','{"en": "LB I"}','Periods:Bronze',5612,NULL,NULL),
(5613,'{"en": "LB IIA"}','{"en": "LB IIA"}','Periods:Bronze',5613,NULL,NULL),
(5614,'{"en": "LB IIB"}','{"en": "LB IIB"}','Periods:Bronze',5614,NULL,NULL),
(5701,'{"en": "Ir"}','{"en": "Ir"}','Periods:Iron',5701,NULL,NULL),
(5702,'{"en": "Ir IA"}','{"en": "Ir IA"}','Periods:Iron',5702,NULL,NULL),
(5703,'{"en": "Ir IB"}','{"en": "Ir IB"}','Periods:Iron',5703,NULL,NULL),
(5704,'{"en": "Ir IIA"}','{"en": "Ir IIA"}','Periods:Iron',5704,NULL,NULL),
(5705,'{"en": "Ir IIB"}','{"en": "Ir IIB"}','Periods:Iron',5705,NULL,NULL),
(5706,'{"en": "Ir IIC"}','{"en": "Ir IIC"}','Periods:Iron',5706,NULL,NULL),
(5901,'{"en": "Early Hellenistic"}','{"en": "Hellenistic"}','Periods:Hellenistic',1,NULL,NULL),
(5902,'{"en": "Late Hellenistic"}','{"en": "Late Hellenistic"}','Periods:Hellenistic',2,NULL,NULL),
(6001,'{"en": "Early Roman"}','{"en": "Early Roman"}','Periods:Roman',1,NULL,NULL),
(6002,'{"en": "Herodian"}','{"en": "Herodian"}','Periods:Roman',2,NULL,NULL),
(6003,'{"en": "Middle Roman"}','{"en": "Middle Roman"}','Periods:Roman',3,NULL,NULL),
(6004,'{"en": "Late Roman"}','{"en": "Late Roman"}','Periods:Roman',4,NULL,NULL),
(6201,'{"en": "Umayyad"}','{"en": "Umayyad"}','Periods:Early-Islamic',1,NULL,NULL),
(6202,'{"en": "Abbasid"}','{"en": "Abbasid"}','Periods:Early-Islamic',2,NULL,NULL),
(6203,'{"en": "Fatimid"}','{"en": "Fatimid"}','Periods:Early-Islamic',3,NULL,NULL),
(6303,'{"en": "Crusader"}','{"en": "Crusader"}','Periods:Medieval',3,NULL,NULL),
(6304,'{"en": "Ayyubid"}','{"en": "Ayyubid"}','Periods:Medieval',4,NULL,NULL),
(6305,'{"en": "Mamluk"}','{"en": "Mamluk"}','Periods:Medieval',5,NULL,NULL),
(6501,'{"en": "1917-1948"}','{"en": "1917-1948"}','Periods:Modern',1,NULL,NULL),
(6502,'{"en": "1949-present"}','{"en": "1949-present"}','Periods:Modern',2,NULL,NULL);

